
!     /BMDAT/
!       SD       ABSORPTION COEFFICIENT MOLECULAR BAND MODEL PARAMETERS
!                FOR THE CURRENT SPECTRAL FREQUENCY BIN [CM-1 / ATM].
!       OD       LINE SPACING MOLECULAR BAND MODEL PARAMETERS FOR THE
!                CURRENT SPECTRAL FREQUENCY BIN [CM].
!       ALF0     THE STP LORENTZ/COLLISION LINE WIDTH PARAMETERS FOR
!                THE CURRENT SPECTRAL FREQUENCY BIN [CM-1].
!       DOP0     THE STP DOPPLER LINE WIDTH PARAMETERS FOR THE CURRENT
!                SPECTRAL FREQUENCY BIN [CM-1].
      INTEGER IPCN,IPTL,IBINCN,IBINTL,IMOLCN,IMOLTL,IALFCN
      REAL SDZCN,ODZCN,SDZ0TL,SDZ1TL,SDZ2TL,SDZ3TL,SDZ4TL,              &
     &  DOP0,ALF0,SDCN,SDTL,ODCN
      COMMON/BMDAT/SDZCN(MTEMP),ODZCN(MTEMP),SDZ0TL(MTEMP,MPRES),       &
     &  SDZ1TL(MTEMP,MPRES),SDZ2TL(MTEMP,MPRES),SDZ3TL(MTEMP,MPRES),    &
     &  SDZ4TL(MTEMP,MPRES),DOP0(MMOLT),IPCN,IPTL,IBINCN,IBINTL,        &
     &  IMOLCN,IMOLTL,IALFCN,ALF0(MMOLT),SDCN(MTEMP,MMOLT),             &
     &  SDTL(0:NTLSUB,1:MTEMP,1:MPRES,1:MMOLT),ODCN(MTEMP,MMOLT)
      SAVE /BMDAT/
