
!     /BMHEAD/  BAND MODEL PARAMETER FILE HEADER:
!       LRECCN   RECORD NUMBER OF LAST RECORD IN BMNAMECN FILE.
!       LRECTL   RECORD NUMBER OF LAST RECORD IN BMNAMETL FILE.
!       NTEMP    NUMBER OF TEMPERATURES IN BAND MODEL PARAMETER GRID.
!       NPRESS   NUMBER OF PRESSURES IN LINE-TAIL BAND MODEL
!                PARAMETER GRID.
!       MBINBM   BIN NUMBER OF LAST MOLECULAR BAND MODEL SPECTRAL POINT.
!       BNDWID   SPECTRAL WIDTH OF BAND MODEL INTERVAL [CM-1].
!       HBNDWD   HALF SPECTRAL WIDTH OF BAND MODEL INTERVAL [CM-1].
!       MXFREQ   MAXIMUM FREQUENCY OF BAND MODEL DATA.
!       EDGENR   LINE CENTER TO SPECTRAL BIN NEARER EDGE
!                DISTANCE OVER SPECTRAL BIN WIDTH.
!       EDGEFR   LINE CENTER TO SPECTRAL BIN FURTHER EDGE
!                DISTANCE OVER SPECTRAL BIN WIDTH.

!                |<-------------------------->|                 d
!                |<------>|   BNDWID          |      EDGENR = ------
!                |    d   |                   |               BNDWID
!                |      _/ \_                 |
!                |_____/     \________________|    EDGEFR = 1 - EDGENR

!       EDGEDF   EDGEFR MINUS EDGENR.
!       ADTEST   CONSTANT USED TO DETERMINE IF DOPPLER WIDTH
!                REQUIRES EXPLICIT INTEGRATION OF THE VOIGT (SERTRAN)
!                FINITE BIN EQUIVALENT WIDTH [CM-1].
!       OSHIFT   0.05 CM-1 (SHIFT FOR OUTPUT OF 0.1 CM-1 BAND MODEL).
!       DELSUB   LINE TAIL EVLAUATION POINTS, NORMALIZED ONTO [-1,1].
!       PBAND    BAND MODEL PARAMETER PRESSURE GRID FOR SERTRAN.
!       TBAND    BAND MODEL PARAMETER TEMPERATURE GRID.
      INTEGER LRECCN,LRECTL,NTEMP,NPRESS,MBINBM
      REAL BNDWID,HBNDWD,MXFREQ,EDGENR,EDGEFR,EDGEDF,                   &
     &  ADTEST,TBAND,PBAND,OSHIFT,DELSUB
      COMMON/BMHEAD/LRECCN,LRECTL,NTEMP,NPRESS,MBINBM,                  &
     &  BNDWID,HBNDWD,MXFREQ,EDGENR,EDGEFR,EDGEDF,ADTEST,OSHIFT,        &
     &  DELSUB(0:NTLSUB),PBAND(MPRES),TBAND(MTEMP)
