
!     /BMPATH/
!       PTLOS    LINE-OF-SIGHT SEGMENT PRESSURE TIMES SEGMNT TEMPERATURE
!                OVER 273.15K, THE QUOTIENT RAISED TO -0.75 [ATM].
!       PTMS     PT SCALING FOR VERTICAL MS PATH SEGMENTS [ATM].
!       P2LOS    LOS SEGMENT PRESSURE SQUARED INTERPOLATION FRACTION.
!       P2MS     VERTICAL MS SEGMENT P-SQUARED INTERPOLATION FRACTION.
!       T5LOS    SQUARE ROOT OF LOS SEGMENT TEMPERATURE OVER 273.15K.
!       T5MS     SQRT(T/273.15K) FOR VERTICAL MS PATH SEGMENTS.
!       JTLOS    BAND MODEL TEMPERATURE-GRID UPPER INDEX FOR LOS PATHS.
!       JTMS     BAND MODEL TEMPERATURE-GRID UPPER INDEX FOR MS PATH.
!       KTLOS    X-SECTION TEMPERATURE-GRID UPPER INDEX FOR LOS PATHS.
!       KTMS     X-SECTION TEMPERATURE-GRID UPPER INDEX FOR MS PATH.
!       FTLOS    TEMPERATURE INTERPOLATION FRACTION USED WITH JTLOS.
!       FTMS     TEMPERATURE INTERPOLATION FRACTION USED WITH JTMS.
!       GTLOS    TEMPERATURE INTERPOLATION FRACTION USED WITH KTLOS.
!       GTMS     TEMPERATURE INTERPOLATION FRACTION USED WITH KTMS.
      INTEGER JTLOS,JTMS,KTLOS,KTMS
      REAL PTLOS,PTMS,P2LOS,P2MS,T5LOS,T5MS,FTLOS,FTMS,GTLOS,GTMS
      COMMON/BMPATH/PTLOS(LAYTWO,MLOS),PTMS(LAYDIM),                    &
     &  P2LOS(LAYTWO,MLOS),P2MS(LAYDIM),T5LOS(LAYTWO,MLOS),T5MS(LAYDIM),&
     &  JTLOS(LAYTWO,MLOS),JTMS(LAYDIM),KTLOS(LAYTWO,MLOS),KTMS(LAYDIM),&
     &  FTLOS(LAYTWO,MLOS),FTMS(LAYDIM),GTLOS(LAYTWO,MLOS),GTMS(LAYDIM)
      SAVE /BMPATH/
