      SUBROUTINE CD2E

!     PROCESS CARD2E INPUTS:
      IMPLICIT NONE

!     PARAMETERS:
      INCLUDE 'PARAMS.h'

!     COMMONS:

!     /USSPC/
      INTEGER NARSPC
      REAL VARSPC
      LOGICAL LARUSS
      COMMON/USSPC/NARSPC(4),VARSPC(4,NWAVLN),LARUSS

!     /CARD2/
!       IHAZE    BOUNDARY LAYER AEROSOL MODEL NUMBER.
!       ISEASN   SEASON NUMBER (1=SPRING-SUMMER, 2=FALL-WINTER).
!       IVULCN   VOLCANIC AEROSOL MODEL NUMBER.
!       ICSTL    COASTAL AIRMASS MODEL NUMBER.
!       ICLD     CLOUD MODEL NUMBER.
!       IVSA     VERTICAL STRUCTURE ALGORITHM (0=OFF, 1=ON).
!       VIS      SURFACE VISIBILITY (GROUND METEOROLOGICAL RANGE) [KM].
!       WSS      CURRENT WIND SPEED (M/S).
!       WHH      24-HOUR WIND SPEED (M/S).
!       RAINRT   RAIN RATE (MM/HR)
!       LSAP     LOGICAL FLAG FOR SPECTRAL AEROSOL PROFILES INPUT.
      INTEGER IHAZE,ISEASN,IVULCN,ICSTL,ICLD,IVSA
      REAL VIS,WSS,WHH,RAINRT
      LOGICAL LSAP
      COMMON/CARD2/IHAZE,ISEASN,IVULCN,ICSTL,ICLD,IVSA,                 &
     &  VIS,WSS,WHH,RAINRT,LSAP

!     READ CARD2E:
      IF(LARUSS)THEN
          CALL ARUEXA
      ELSE
          NARSPC(1)=0
          NARSPC(2)=0
          NARSPC(3)=0
          NARSPC(4)=0
          IF(IHAZE.EQ.7 .OR. ICLD.EQ.11)CALL RDEXA
      ENDIF

!     RETURN TO DRIVER:
      RETURN
      END
