
!     CHANNEL SPECTRAL RESPONSE COMMONS:

!     /CHANEL/
!       VLCHAN   VALUE OF INTEGRATION OVER CHANNEL
!                  (IN-BAND RADIANCE [W SR-1 CM-2] IF IEMSCT=1 OR =2,
!                  IN-BAND EXTINCTION IF IEMSCT=0, AND TRANSMITTED
!                  SOLAR IRRADIANCE [W CM-2] IF IEMSCT=3).
!       WTCHN    LIST OF WEIGHTS FOR EACH SPECTRAL BIN.
!       WDFREQ   INTEGRATED WIDTH OF CHANNEL [CM-1].
!       WDWAVE   INTEGRATED WIDTH OF CHANNEL
!                  [NANOMETERS IF UNTFLG='N', OTHERWISE MICRONS].
!       SPECLO   MINIMUM CHANNEL SPECTRAL POINT [MICRONS IF UNTFLG='M',
!                  NANOMETERS IF UNTFLG='N', OTHERWISE WAVENUMBERS].
!       SPECHI   MAXIMUM CHANNEL SPECTRAL POINT [MICRONS IF UNTFLG='M',
!                  NANOMETERS IF UNTFLG='N', OTHERWISE WAVENUMBERS].
!       MOM1ST   CHANNEL FIRST SPECTRAL MOMENT.
!       M2DIFF   CHANNEL SECOND SPECTRAL MOMENT DIFFERENCE INTEGRAL.
!       LENCHN   LENGTH OF FILTER RESPONSE FUNCTION OUTPUT FILE NAME.
!       NCHAN    TOTAL NUMBER OF BAND PASS CHANNELS.
!       LNCHAN   LENGTH OF CHANNEL NAME.
!       NFRQLO   FREQUENCY OF MINIMUM CALCULATIONAL SPECTRAL BIN [CM-1].
!       NFRQHI   FREQUENCY OF MAXIMUM CALCULATIONAL SPECTRAL BIN [CM-1].
!       NUMCHN   NUMBER OF CHANNELS FOR EACH SPECTRAL BIN.
!       LSTCHN   LIST OF CHANNEL NUMBERS FOR EACH SPECTRAL BIN.
      DOUBLE PRECISION VLCHAN
      REAL WTCHN,WDFREQ,WDWAVE,SPECLO,SPECHI,MOM1ST,M2DIFF
      INTEGER LENCHN,NCHAN,LNCHAN,NFRQLO,NFRQHI,NUMCHN,LSTCHN
      COMMON/CHANEL/VLCHAN(MOUT,MLOS,MXCHAN),WTCHN(MXNCHN,MNBIN:MXBIN), &
     &  WDFREQ(MXCHAN),WDWAVE(MXCHAN),SPECLO(MXCHAN),SPECHI(MXCHAN),    &
     &  MOM1ST(MXCHAN),M2DIFF(MXCHAN),LENCHN,NCHAN,LNCHAN(MXCHAN),      &
     &  NFRQLO(MXCHAN),NFRQHI(MXCHAN),NUMCHN(MNBIN:MXBIN),              &
     &  LSTCHN(MXNCHN,MNBIN:MXBIN)

!    /CCHANL/
!       UNTFLG   SPECTRAL GRID UNIT FLAG ['W' for Wavenumbers,
!                'M' for Microns, and 'N' for Nanometers].
!       CHNOUT   FILTER RESPONSE FUNCTION OUTPUT FILE NAME.
!       NMCHAN   CHANNEL NAME (MAXIMUM OF 80 CHARACTERS).
!       C_STAR   STAR (*) LABEL FOR INACCURATE BRIGHTNESS TEMPERATURE.
      CHARACTER UNTFLG*1,CHNOUT*100,NMCHAN*80,C_STAR*1
      COMMON/CCHANL/UNTFLG,CHNOUT,NMCHAN(MXCHAN),C_STAR(MXCHAN)
