      MODULE CIRMOD

!         CIRMOD CONTAINS CIRRUS CLOUD DATA FROM AN EXTERNAL FILE.
!           CIRTIT   CIRRUS CLOUD TYPE OR NAME.
!           NCIRAN   NUMBER OF CIRRUS CLOUD SCATTERING PHASE
!                    FUNCTION ANGULAR GRID POINTS.
!           NCIRLG   NUMBER OF CIRRUS CLOUD SCATTERING PHASE FUNCTION
!                    LEGENDRE POLYNOMIAL EXPANSION COEFFICIENTS.
!           NCIRWV   NUMBER OF CIRRUS CLOUD SPECTRAL GRID POINTS.
!           ICIRAN   LOOP INDEX FOR CIRRUS CLOUD SCATTERING PHASE
!                    FUNCTION ANGULAR GRID POINTS.
!           ICIRLG   LOOP INDEX FOR CIRRUS CLOUD SCATTERING PHASE
!                    FUNCTION LEGENDRE POLYNOMIAL EXPANSION COEFFICIENTS.
!           ICIRWV   LOOP INDEX FOR CIRRUS CLOUD SPECTRAL GRID POINTS.
!           CIRANG   CIRRUS CLOUD SCATTERING PHASE FUNCTION ANGULAR
!                    GRID [DEGREES].
!           CIRCOS   CIRRUS CLOUD SCATTERING PHASE FUNCTION COSINE GRID.
!           CIRWAV   CIRRUS CLOUD SCATTERING PHASE FUNCTION SPECTRAL
!                    GRID [MICRONS].
!           CIREXT   CIRRUS CLOUD EXTINCTION COEFFICIENTS [KM-1 M3 / G].
!           CIRABS   CIRRUS CLOUD ABSORPTION COEFFICIENTS [KM-1 M3 / G].
!           CIRPF    CIRRUS CLOUD PHASE FUNCTION [SR-1, 4 pi NORMALIZED].
!           CIRLEG   CIRRUS CLOUD SCATTERING PHASE FUNCTION LEGENDRE
!                    POLYNOMIAL EXPANSION COEFFICIENTS.
!           CIRPFV   CIRRUS CLOUD PHASE FUNCTION INTERPOLATED TO A
!                    SPECTRAL WAVELENGTH [SR-1, 4 pi NORMALIZED].
          CHARACTER CIRTIT*80
          INTEGER NCIRAN, NCIRLG, NCIRWV, ICIRAN, ICIRLG, ICIRWV
          REAL, ALLOCATABLE :: CIRANG(:), CIRCOS(:), CIRWAV(:),         &
     &      CIREXT(:), CIRABS(:), CIRPF(:,:), CIRLEG(:,:), CIRPFV(:)
      END MODULE CIRMOD
