      SUBROUTINE CRDEAL

!     THIS ROUTINE DEALLOCATES USER-DEFINED CLOUD SPECTRAL DATA.

!     MODULES:
      USE CLDMOD
      USE CIRMOD

!     DEALLOCATE AND RETURN:
      DEALLOCATE(CLDANG,CLDCOS,CLDWAV,CLDEXT,CLDABS,CLDPF,CLDLEG,CLDPFV)
      DEALLOCATE(CIRANG,CIRCOS,CIRWAV,CIREXT,CIRABS,CIRPF,CIRLEG,CIRPFV)
      RETURN
      END
