      SUBROUTINE CRDRIV

!     THIS ROUTINE IS THE DRIVER FOR CLOUD/RAIN MODELS 1 THROUGH 10.
      IMPLICIT NONE

!     LOCAL VARIABLES:
      DOUBLE PRECISION CTHICK
      REAL CWDCOL,CIPCOL

!     DETERMINE CLOUD/RAIN DENSITY PROFILES
      CALL CRPROF(CTHICK,CWDCOL,CIPCOL)

!     MERGE OLD ATMOSPHERIC AND CLOUD/RAIN LAYER BOUNDARY DATA.
      CALL CRMERG

!     DETERMINE CLOUD/RAIN SPECTRAL DATA
      CALL CRSPEC(SNGL(CTHICK),CWDCOL,CIPCOL)

!     RETURN TO MODTRAN DRIVER ROUTINE
      RETURN
      END
