      FUNCTION   CXDTA(V,IWL,IWH,CP,IND)

!     THIS FUNCTION IS A BIT DIFFERENT FROM AND REPLACES
!     THE OLD ROUTINE, A SUBROUTINE, CXDTA

!     THIS SUBROUTINE FINDS THE C' FOR THE WAVENUMBER V.
!     INPUT:         V --- WAVENUMBER
!            (IWL,IWH) --- WAVENUMBER PAIR SPECIFIES THE ABSORPTION
!                          REGION. BOTH ARE ARRAYS AND TERMINATED
!                          WITH THE VALUE -999
!                   CP --- ARRAY CONTAINS THE C'S
!     I/O:         IND --- INDICATOR INDICATES THE ABSORPTION REGION
!                          WHERE THE WAVENUMBER IS EXPECTED TO BE IN
!                          OR NEARBY (IT SERVES FOR THE PURPOSE
!                          TO SPEED UP THE SEARCHING PROCESS)
      DIMENSION IWL(*),IWH(*),CP(*)
      IV=INT(V)
      CXDTA=-20.0
      IF (IWL(IND+1) .EQ. -999 .AND. IV .GT. IWH(IND)) RETURN
      IF (IV .LT. IWL(1)) RETURN
      IC=0
  100 IF (IV .GE. IWL(IND) .AND. IV .LE. IWH(IND)) GO TO 200
      IF (IV .GT. IWH(IND) .AND. IV .LT. IWL(IND+1)) RETURN
      IND=IND+1
      IF (IWL(IND) .NE. -999) GO TO 100
      IND=IND-1
      IF (IV .GT. IWH(IND)) RETURN
      IND=1
      GO TO 100
  200 IF (IND .EQ. 1) GO TO 400
      INDM1=IND-1
      DO 300 I=1,INDM1
        IC=IC+(IWH(I)-IWL(I))/5+1
  300 CONTINUE
  400 IC=IC+(IV-IWL(IND))/5+1
      CXDTA=CP(IC)
      RETURN
      END
