      REAL FUNCTION DBLTX(W,CPRIME,QA)

!     DOUBLE EXPONENTIAL TRANSMITTANCE ROUTINE.
      IMPLICIT NONE

      REAL W,CPRIME,QA,QAWS

!     NO OPTICAL DEPTH
      DBLTX=1.
      IF(W.LT.1.E-20 .OR. CPRIME.LE.-20.)RETURN
      QAWS=QA*(LOG10(W)+CPRIME)
      IF(QAWS.LE.-6.)RETURN

!     OPTICAL DEPTH OVERFLOW
      DBLTX=0.
      IF(QAWS.GE.2.)RETURN

!     STANDARD TRANSMITTANCE
      DBLTX=EXP(-10.**QAWS)
      RETURN
      END
