      DOUBLE PRECISION FUNCTION DISBBF(T,V)

!     PLANCK BLACK BODY FUNCTION [WATTS CM-2 STER-1 / CM-1].

!     DECLARE ARGUMENTS:
!       T        TEMPERATURE [K].
!       V        FREQUENCY [CM-1].
      DOUBLE PRECISION T,V

!     COMMONS:

!     /RCNSTN/
!       PI       THE CONSTANT PI
!       DEG      NUMBER OF DEGREES IN ONE RADIAN.
!       BIGNUM   MAXIMUM SINGLE PRECISION NUMBER.
!       BIGEXP   MAXIMUM EXPONENTIAL ARGUMENT WITHOUT OVERFLOW.
!       RRIGHT   SMALLEST SINGLE PRECISION REAL ADDED TO 1 EXCEEDS 1.
      REAL PI,DEG,BIGNUM,BIGEXP,RRIGHT
      COMMON/RCNSTN/PI,DEG,BIGNUM,BIGEXP,RRIGHT

!     DECLARE LOCAL VARIABLES:
!       X        EXPONENT USED IN PLANCK FUNCTION.
      REAL X
      DISBBF=DBLE(0.)
      IF(V.LE.0.)RETURN
      X=1.438786*REAL(V/T)

!     PROTECT AGAINST EXPONENTIAL OVERFLOW
      IF(X.GT.BIGEXP)RETURN
      DISBBF=DBLE(1.190956E-12/(EXP(X)-1.))*V**3
      RETURN
      END
