      DOUBLE PRECISION FUNCTION DPRARF(ALT,RSCLHT,GAMMA0)

!     RETURNS RECIPROCAL OF THE RADIUS OF CURVATURE OF THE REFRACTED RAY

!     ARGUMENTS:
!       ALT      ALTITUDE [KM].
!       RSCLHT   RECIPROCAL OF THE REFRACTIVITY SCALE HEIGHT [KM-1].
!       GAMMA0   REFRACTIVITY EXTRAPOLATED DOWN TO 0 KM ALTITUDE.
      DOUBLE PRECISION ALT,RSCLHT,GAMMA0

!     LOCAL VARIABLES:
!       REFRAC   REFRACTIVITY.
      DOUBLE PRECISION REFRAC

!     RECIPROCAL OF THE RADIUS OF CURVATURE:
      REFRAC=GAMMA0*EXP(-RSCLHT*ALT)
      DPRARF=RSCLHT*REFRAC/(1+REFRAC)
      RETURN
      END
