      SUBROUTINE DPSCHT(Z1,Z2,RFNDX1,RFNDX2,RSCLHT,GAMMA0)

!     DPSCHT CALCULATES THE RECIPROCAL SCALE HEIGHT OF THE REFRACTIVITY.

!     INPUT ARGUMENTS:
!       Z1       LOWER ALTITUDE LEVEL (KM).
!       Z2       UPPER ALTITUDE LEVEL (KM).
!       RFNDX1   REFRACTIVITY AT Z1.
!       RFNDX2   REFRACTIVITY AT Z2.

!     OUTPUT ARGUMENTS:
!       RSCLHT   RECIPROCAL OF THE REFRACTIVITY SCALE HEIGHT [KM-1].
!       GAMMA0   REFRACTIVITY EXTRAPOLATED DOWN TO 0 KM ALTITUDE.
      DOUBLE PRECISION Z1,Z2,RFNDX1,RFNDX2,RSCLHT,GAMMA0

!     ASSUME REFRACTIVITY IS NON-NEGATIVE AND Z2-Z1 IS NON-ZERO:
      RSCLHT=LOG((RFNDX1+1.D-30)/(RFNDX2+1.D-30))/(Z2-Z1)
      GAMMA0=RFNDX1*EXP(RSCLHT*Z1)
      RETURN
      END
