
!     JMASS ERROR HANDLING PARAMETERS AND COMMONS:

      INTEGER MAXERR
      PARAMETER(MAXERR=500)

!     /ERRORDATA/
      INTEGER OUTPUTCOUNT,ERRORCODE,LSTERR
      COMMON/ERRORDATA/OUTPUTCOUNT,ERRORCODE,LSTERR

!     /ERRORCHAR/
      CHARACTER ERRORBUF*512
      COMMON/ERRORCHAR/ERRORBUF(0:MAXERR)
