      REAL FUNCTION EXPINT(X1,X2,A)

!     REAL EXPONENTIAL INTERPOLATION FOR POSITIVE ARGUMENTS.
      REAL X1,X2,A
      IF(X1.GT.0. .AND. X2.GT.0.)THEN
          EXPINT=X1*(X2/X1)**A
      ELSE
          EXPINT=X1+(X2-X1)*A
      ENDIF
      RETURN
      END
      DOUBLE PRECISION FUNCTION DPEXNT(X1,X2,A)

!     DOUBLE PRECISION EXPONENTIAL INTERPOLATION FOR POSITIVE ARGUMENTS.
      DOUBLE PRECISION X1,X2,A
      IF(X1.GT.0.D0 .AND. X2.GT.0.D0)THEN
          DPEXNT=X1*(X2/X1)**A
      ELSE
          DPEXNT=X1+(X2-X1)*A
      ENDIF
      RETURN
      END
