      SUBROUTINE FLCLOS(NMOLYS,NMOLY,NOPRNT)

!     ROUTINE TO CLOSE MODTRAN FILES:
      IMPLICIT NONE

!     ARGUMENTS:
!       NOPRNT   PRINT FLAG.
      INTEGER NMOLYS,NMOLY,NOPRNT

!     COMMONS:
      INCLUDE 'IFIL.h'

!     /CJM5/
!       AMOD3D   FLAG INDICATING OUTPUT DATABASE FILE TYPE:
      CHARACTER AMOD3D*1
      COMMON/CJM5/AMOD3D

!     LOCAL VARIABLES:
!       LOPEN    OPEN FILE FLAG.
      LOGICAL LOPEN
      INTEGER I

!     DATA:
!       SVSTAT   FILE SAVE STATUS, SET TO 'KEEP' FOR DEBUGGING.
!       DATASV   FILE SAVE STATUS FOR DATABASE FILES.
      CHARACTER SVSTAT*6,DATASV*6
      DATA SVSTAT/'KEEP'/
!DEL  DATA SVSTAT/'DELETE'/
      DATA DATASV/'DELETE'/
!DB   DATA DATASV/'KEEP'/

!       ITBY(*,*)   MOLECULAR BAND MODEL FILE FOR THE Y-SPECIES.
!                   THE FIRST INDEX SELECTS THE Y-SPECIES; THE SECOND,
!                   EITHER 1 OR 2, SELECTS CENTER/TAIL BAND MODEL FILE.
      DO I=1,NMOLYS

!        THESE ARE BAND MODEL SPECIES WITH TWO PARAMETER FILES EACH.
         INQUIRE(ITBY(I,1),OPENED=LOPEN)
         IF(LOPEN)CLOSE(ITBY(I,1))
         INQUIRE(ITBY(I,2),OPENED=LOPEN)
         IF(LOPEN)CLOSE(ITBY(I,2))
      ENDDO
      DO I=NMOLYS+1,NMOLY

!        THESE ARE CROSS-SECTIONS SPECIES LIKE THE CFCS W/ 1 FILE EACH.
         INQUIRE(ITBY(I,1),OPENED=LOPEN)
         IF(LOPEN)CLOSE(ITBY(I,1))
      ENDDO

!     DELETE ALL OPEN MODTRAN I/O FILES AND CLOSE DATA/SCRATCH FILES:
      INQUIRE(IRD,OPENED=LOPEN)
      IF(LOPEN)CLOSE(IRD,STATUS='KEEP')
      IF(NOPRNT.EQ.3)THEN

!         DELETE TAPE3 IF NOPRNT EQUALS 3 ON THE LAST RUN:
          INQUIRE(IPR,OPENED=LOPEN)
          IF(LOPEN)CLOSE(IPR,STATUS='DELETE')
      ELSE
          INQUIRE(IPR,OPENED=LOPEN)
          IF(LOPEN)CLOSE(IPR,STATUS=SVSTAT)
      ENDIF
      INQUIRE(IPU,OPENED=LOPEN)
      IF(LOPEN)CLOSE(IPU,STATUS='KEEP')
      INQUIRE(IPR1,OPENED=LOPEN)
      IF(LOPEN)CLOSE(IPR1,STATUS=SVSTAT)
      INQUIRE(ITBCN,OPENED=LOPEN)
      IF(LOPEN)CLOSE(ITBCN,STATUS='KEEP')
      INQUIRE(ITBTL,OPENED=LOPEN)
      IF(LOPEN)CLOSE(ITBTL,STATUS='KEEP')
      INQUIRE(ITBX,OPENED=LOPEN)
      IF(LOPEN)CLOSE(ITBX,STATUS='KEEP')
      INQUIRE(ISCRCH,OPENED=LOPEN)
      IF(LOPEN)CLOSE(ISCRCH)
      INQUIRE(IPLOT,OPENED=LOPEN)
      IF(LOPEN)CLOSE(IPLOT,STATUS=SVSTAT)
      INQUIRE(JPUSCR,OPENED=LOPEN)
      IF(LOPEN)CLOSE(JPUSCR,STATUS=SVSTAT)
      INQUIRE(IPUSCN,OPENED=LOPEN)
      IF(LOPEN)CLOSE(IPUSCN,STATUS=SVSTAT)
      INQUIRE(IPTSCN,OPENED=LOPEN)
      IF(LOPEN)CLOSE(IPTSCN,STATUS=SVSTAT)
      INQUIRE(IFLUX,OPENED=LOPEN)
      IF(LOPEN)CLOSE(IFLUX,STATUS=SVSTAT)
      INQUIRE(ICR,OPENED=LOPEN)
      IF(LOPEN)CLOSE(ICR,STATUS=SVSTAT)
      INQUIRE(IDBIN,OPENED=LOPEN)
      IF(LOPEN)CLOSE(IDBIN,STATUS='KEEP')
      INQUIRE(IDBOUT,OPENED=LOPEN)
      IF(LOPEN)THEN
          IF(AMOD3D.EQ.'C' .OR. AMOD3D.EQ.'M')THEN
              CLOSE(IDBOUT,STATUS='KEEP')
          ELSE
              CLOSE(IDBOUT,STATUS=DATASV)
          ENDIF
      ENDIF
      INQUIRE(I3DGEN,OPENED=LOPEN)
      IF(LOPEN)CLOSE(I3DGEN,STATUS=DATASV)
      INQUIRE(I3DCNT,OPENED=LOPEN)
      IF(LOPEN)CLOSE(I3DCNT,STATUS=DATASV)
      INQUIRE(I3DDAT,OPENED=LOPEN)
      IF(LOPEN)CLOSE(I3DDAT,STATUS=DATASV)
      INQUIRE(I3DMOL,OPENED=LOPEN)
      IF(LOPEN)CLOSE(I3DMOL,STATUS=DATASV)
      INQUIRE(ICHNUN,OPENED=LOPEN)
      IF(LOPEN)CLOSE(ICHNUN,STATUS='KEEP')

      INQUIRE(JPU,OPENED=LOPEN)
      IF(LOPEN)CLOSE(JPU,STATUS='KEEP')
      INQUIRE(JPR1,OPENED=LOPEN)
      IF(LOPEN)THEN
         CALL PUTINT(-9898)
         CALL BFLUSH()
         CLOSE(JPR1,STATUS=SVSTAT)
      ENDIF
      INQUIRE(JPLOT,OPENED=LOPEN)
      IF(LOPEN)CLOSE(JPLOT,STATUS=SVSTAT)
      INQUIRE(IALB,OPENED=LOPEN)
      IF(LOPEN)CLOSE(IALB,STATUS='KEEP')
      INQUIRE(ITKDIS,OPENED=LOPEN)
      IF(LOPEN)CLOSE(ITKDIS,STATUS='KEEP')
      INQUIRE(IRKDIS,OPENED=LOPEN)
      IF(LOPEN)CLOSE(IRKDIS,STATUS='KEEP')
      INQUIRE(JTKDIS,OPENED=LOPEN)
      IF(LOPEN)CLOSE(JTKDIS,STATUS='KEEP')
      INQUIRE(JRKDIS,OPENED=LOPEN)
      IF(LOPEN)CLOSE(JRKDIS,STATUS='KEEP')
      INQUIRE(LPATH,OPENED=LOPEN)
      IF(LOPEN)CLOSE(LPATH,STATUS='KEEP')
      INQUIRE(ISAP,OPENED=LOPEN)
      IF(LOPEN)CLOSE(ISAP,STATUS='KEEP')
      RETURN
      END
