      REAL FUNCTION HERTDA(V)

!     HERZBERG O2 ABSORPTION [CM-1/ATM AT 273.15]
!     HALL,1987 PRIVATE COMMUNICATION, BASED ON:

!     REF. JOHNSTON ET.AL, JGR,89,11661-11665,1984
!         NICOLET, 1987 (RECENT STUDIES IN ATOMIC & MOLECULAR PROCESSES,
!                        PLEMUN PUBLISHING CORP, NY 1987)
!     AND YOSHINO, ET.AL., 1988 (PREPRINT OF "IMPROVED ABSORPTION
!         CROSS SECTIONS OF OXYGEN IN THE WAVELENGTH REGION 205-240NM
!         OF THE HERZBERG CONTINUUM")

!     INPUT ARGUMENTS:
!       V        SPECTRAL FREQUENCY [CM-1].
      REAL V

!     BRANCH BASED ON SPECTRAL FREQUENCY
      IF(V.LE.36000.)THEN
          HERTDA=0.
      ELSE

!         EXTRAPOLATE SMOOTHLY THROUGH THE HERZBERG BAND REGION
!         NOTE: HERZBERG BANDS ARE NOT CORRECTLY INCLUDED
!         HALL'S HERZBERG  (LEAST SQRS FIT, LN(P))
          HERTDA=3.7893E-9*V*EXP(-69.738*(ALOG(V)-10.79571)**2)

!         CORRECTION FACTOR
          IF(V.LT.40000.)HERTDA=HERTDA-5.3175E-11*(40000-V)
      ENDIF
      RETURN
      END
