
!     NOTE: MAKE MYMOL SAME AS MMOLY IN PARAMS.h
      INTEGER MYMOL
      PARAMETER(MYMOL=50)

!     /IFIL/ FILE UNIT NUMBERS (DEFINED IN devcbd.f)
!       NPR      PRINTOUT LEVEL SWITCH (1=SMALL,0=NORMAL,-1=LARGE).
!       IRD      01 PRIMARY INPUT FILE:
!                   tape5 or <ROOTNAME>.tp5, ASCII.
!       IPR      02 PRIMARY OUTPUT FILE:
!                   tape6 or <ROOTNAME>.tp6, ASCII.
!       IROOT    03 ROOTNAME FILE: 'mod5root.in' or 'MOD5ROOT.IN'.
!       IPU      07 SPECTRAL DATA FILE:
!                   tape7 or <ROOTNAME>.tp7, ASCII.
!       IPR1     08 LINE-OF-SIGHT MULTIPLE SCATTERING FILE:
!                   tape8 or <ROOTNAME>.tp8, ASCII.
!       ITBCN    09 LINE CENTER MOLECULAR BAND MODEL DATA, IN BINARY.
!                   'DATA/01_2007c.bin' OR <BMPREFIX>c.bin
!       ITBTL    10 LINE TAIL MOLECULAR BAND MODEL DATA, IN BINARY.
!                   'DATA/01_2007t.bin' OR <BMPREFIX>t.bin
!       ITBX     11 MOLECULAR (CFC) ABSORPTION COEFFICIENT DATA.
!                   'DATA/CFC03_p1.ASC', 'DATA/CFC03_01.ASC',
!                   'DATA/CFC03_05.ASC' or 'DATA/CFC03_15.ASC', ASCII.
!       ITBY(*,*)   MOLECULAR BAND MODEL FILE FOR THE Y-SPECIES.
!                   THE FIRST INDEX SELECTS THE Y-SPECIES; THE SECOND,
!                   EITHER 1 OR 2, SELECTS CENTER/TAIL BAND MODEL FILE.
!       ISCRCH   12 MULTIPLE SCATTERING DATA SAVED FOR REPEAT RUNS:
!                   SCRATCH FILE, BINARY.
!       IPLOT    13 SPECTRAL TRANSMITTANCE, RADIANCE OR IRRADIANCE FILE:
!                   pltout or <ROOTNAME>.plt, ASCII.
!       ICHNUN   14 FILTER RESPONSE FUNCTION OUTPUT FILE:
!                   channels.out or <ROOTNAME>.chn, ASCII.
!       IPUSCN   15 SPECTRALLY DEGRADED (SCANNED) tape7 FILE:
!                   tape7.scn or <ROOTNAME>.7sc, ASCII.
!       IPTSCN   16 SPECTRALLY DEGRADED (SCANNED) pltout FILE:
!                   pltout.scn or <ROOTNAME>.psc, ASCII.
!       IFLUX    17 SPECTRAL FLUX FILE:
!                   specflux or <ROOTNAME>.flx, ASCII.
!       ICR      18 SPECTRAL COOLING RATE FILE:
!                   clrates or <ROOTNAME>.clr, ASCII.
!       IDBIN    19 DATABASE INPUT FILE: <ROOTNAME>.dbi, ASCII.
!       IDBOUT   20 DATABASE OUTPUT FILE: <ROOTNAME>.dbo, ASCII.
!       I3DGEN   21 OUTPUT FILE OF GENERAL INFORMATION FOR MOD3D.
!       I3DCNT   22 OUTPUT FILE OF CONTINUA DATA FOR MOD3D.
!       I3DDAT   23 OUTPUT FILE OF MOLECULAR EXTINCTION BY ATMOSPHERE.
!       I3DMOL   24 OUTPUT FILE OF MOLECULAR EXTINCTION DATA FOR MOD3D.
!       IALB     25 SPHERICAL ALBEDO AND DIFFUSE TRANSM OUTPUT FILE.
!                   atmcor.dat or <ROOTNAME>.acd, ASCII.
!       JPU      26 BINARY FORM OF SPECTRAL DATA FILE.
!                   tape7b or <ROOTNAME>b.tp7, BINARY.
!       JPR1     27 MULTIPLE OUTPUT FILES WRITTEN IN BINARY.
!                   tape8b or <ROOTNAME>b.tp8, BINARY.
!       JPLOT    28 SPECTRAL TRANSMITTANCE, RADIANCE OR IRRADIANCE FILE:
!                   pltoutb or <ROOTNAME>b.plt, BINARY.
!       JPUSCR   29 SPECTRAL DATA SAVED FOR REPEAT RUNS:
!                   tape7b.scr or <ROOTNAME>b.7sr, BINARY.
!       ITKDIS   30 k-DISTRIBUTION OF CUMULATIVE TRANSMITTANCES.
!                   t_kdis.dat or <ROOTNAME>.t_k, ASCII.
!       IRKDIS   31 k-DISTRIBUTION OF CUMULATIVE RADIANCES.
!                   r_kdis.dat or <ROOTNAME>.r_k, ASCII.
!       JTKDIS   32 k-DISTRIBUTION OF CUMULATIVE TRANSMITTANCES.
!                   t_kdis.bin or <ROOTNAME>b.t_k, BINARY.
!       JRKDIS   33 k-DISTRIBUTION OF CUMULATIVE RADIANCES.
!                   r_kdis.bin or <ROOTNAME>b.r_k, BINARY.
!       LPATH    34 REFRACTED PATH INPUT FILE.
!                   rfracpth.dat or <ROOTNAME>.pth.
!       ISAP     35 SPECTRAL AEROSOL PROFILE DATA INPUT FILE.
!                   SpecAerProf.dat or <ROOTNAME>.sap.
      INTEGER NPR,IRD,IPR,IROOT,IPU,IPR1,ITBCN,ITBTL,ITBX,              &
     &  ITBY(MYMOL,2),ISCRCH,IPLOT,ICHNUN,IPUSCN,IPTSCN,IFLUX,          &
     &  ICR,IDBIN,IDBOUT,I3DGEN,I3DCNT,I3DDAT,I3DMOL,IALB,JPU,          &
     &  JPR1,JPLOT,JPUSCR,ITKDIS,IRKDIS,JTKDIS,JRKDIS,LPATH,ISAP
      LOGICAL BINOUT
      COMMON/IFIL/NPR,IRD,IPR,IROOT,IPU,IPR1,ITBCN,ITBTL,ITBX,          &
     &  ITBY,ISCRCH,IPLOT,ICHNUN,IPUSCN,IPTSCN,IFLUX,ICR,IDBIN,         &
     &  IDBOUT,I3DGEN,I3DCNT,I3DDAT,I3DMOL,IALB,JPU,JPR1,JPLOT,         &
     &  JPUSCR,ITKDIS,IRKDIS,JTKDIS,JRKDIS,LPATH,ISAP,BINOUT
      SAVE/IFIL/
