      SUBROUTINE INITCD(CHARIN)

!     INITCD ROUTINE FOR TESTING THE APPLICATION PROGRAMMER'S
!     INTERFACE (API) OPTION:  TEST CASE 01 (BUILD MOD3D DATABASE).

!     INPUT ARGUMENTS:
!       CHARIN   CHARACTER STRING LABELING INPUT CARD.
      CHARACTER CHARIN*(*)

!     PARAMETERS:
!       REC4PI   RECIPROCAL OF FOUR PI.
!       NH2O     NUMBER OF H2O PROFILES MINUS ONE (>0).
!       PBOT     SURFACE (GROUND LEVEL) PRESSURE [ATM].
!       PTOP     TOA (TOP-OF-ATMOSPHERE) PRESSURE (>0.) [MBARS].
      INCLUDE 'PARAMS.h'
      INTEGER NH2O
      REAL REC4PI,PBOT,PTOP
      PARAMETER(REC4PI=.07957747,NH2O=5,PBOT=PZERO,PTOP=PBOT/10000.)

!     COMMONS:
      INCLUDE 'BASE.h'
      INCLUDE 'SOLS.h'

!     /JM1/
!       CODE     CODE INPUT FLAG: 'F' OR 'L' FOR LOWTRAN BAND MODEL.
!                                 'T' OR 'M' FOR MODTRAN BAND MODEL.
!                                 'C' OR 'K' FOR CORRELATED-K MODEL.
!       SPEED    COMPUTATIONAL SPEED FLAG USED WITH CK MODEL ['F' OR '2'
!                FOR FAST (12 K'S), 'M' OR '1' FOR MODERATE (17 K'S),
!                AND 'S' OR '0' FOR SLOW (33 K'S); 'S' IS DEFAULT]
!       SURREF   SURFACE REFLECTANCE CHARACTER STRING.
!                IF FIRST NON-BLANK CHARACTER IS "B",
!                  Bi-directional Reflectance Distribution
!                  Function (BRDF) DATA IS READ IN.
!                IF FIRST NON-BLANK CHARACTER IS "L" or "-"
!                  SURFACE IS MODELED AS A LAMBERTIAN REFLECTOR AND
!                  SPECTRAL ALBEDO IS READ FROM FILE "DATA/spec_alb.dat"
!                OTHERWISE, THE CHARACTER STRING IS ASSUMED TO CONTAIN
!                  A SPECTRALLY INDEPENDENT VALUE FOR SURFACE ALBEDO.
      CHARACTER CODE*1,SPEED*1,SURREF*7
      COMMON/JM1/CODE,SPEED,SURREF

!     /CARD1/
!       MODEL    MODEL ATMOSPHERE INDEX.
!       ITYPE    SLANT PATH TYPE.
!       IEMSCT   RADIATIVE TRANSFER MODE.
!                  0 FOR TRANSMITTANCE
!                  1 FOR THERMAL EMISSION ONLY
!                  2 FOR THERMAL EMISSION PLUS SOLAR SCATTER
!                  3 FOR TRANSMITTED SOLAR IRRADIANCE
!                  4 FOR SOLAR SCATTER ONLY
!       M1       MODEL ATMOSPHERE FOR PRESSURE & TEMPERATURE PROFILES.
!       M2       MODEL ATMOSPHERE FOR H2O PROFILE.
!       M3       MODEL ATMOSPHERE FOR O3 PROFILE.
!       I_RD2C   READ CARD 2C, 2C1, ... IF EQUAL 1; SKIP IF EQUAL TO 0.
!       NOPRNT   PRINT FLAG.
!       MODTRN   MODTRAN BAND MODEL FLAG.
      INTEGER MODEL,ITYPE,IEMSCT,M1,M2,M3,I_RD2C,NOPRNT
      LOGICAL MODTRN
      COMMON/CARD1/MODEL,ITYPE,IEMSCT,M1,M2,M3,I_RD2C,NOPRNT,MODTRN

!     /CNTRL/
!       NSEG     NUMBER OF PATH SEGMENTS ALONG LINE-OF-SIGHT.
!       ML       NUMBER OF ATMOSPHERIC PROFILE LEVELS.
!       MLFLX    NUMBER OF LEVELS FOR WHICH FLUX VALUES ARE WRITTEN.
!       IMULT    MULTIPLE SCATTERING FLAG
!                  (0=NONE, 1=AT SENSOR, -1=AT FINAL OR TANGENT POINT).
!       THERML   FLAG TO CALCULATE THERMAL SCATTER.
      INTEGER NSEG,ML,MLFLX,IMULT
      LOGICAL THERML
      COMMON/CNTRL/NSEG(0:MLOSP1),ML,MLFLX,IMULT,THERML

!     /CARD1A/
      INTEGER M4,M5,M6,MDEF,IRD1,IRD2
      COMMON/CARD1A/M4,M5,M6,MDEF,IRD1,IRD2

!     /SURFWV/
!       LAMBER  LOGICAL FLAG, .TRUE. FOR LAMBERTIAN SURFACE.
!       TPTEMP  TARGET-PIXEL SURFACE TEMPERATURES [K].
!       TPHDIR  TARGET-PIXEL HEMISPHERE DIRECTIONAL REFLECTANCE AT
!               VIEWING ANGLES.
!       TPBRDF  TARGET-PIXEL BIDIRECTIONAL REFLECTANCE DISTRIBUTION
!               FUNCTION AT VIEWING AND SUN ANGLES.
!       AATEMP  AREA-AVERAGED GROUND SURFACE TEMPERATURES [K].
!       AASALB  AREA-AVERAGED GROUND SURFACE ALBEDO.
!       AADREF  AREA-AVERAGED GROUND SURFACE DIRECTIONAL REFLECTIVITY
!               AT THE SOLAR ZENITH ANGLE.
!       EMU     GROUND DIRECTIONAL EMISSIVITY AT VIEWING ANGLES.
!       BEM     GROUND DIRECTIONAL EMISSIVITY AT QUADRATURE ANGLES.
!       RMU     GROUND BRDF AZIMUTH COMPONENTS AT VIEWING ANGLES
!               AND AT SUN (=0) OR QUADRATURE (>0) ANGLE.
!       BDR     GROUND BRDF AZIMUTH COMPONENTS AT QUADRATURE ANGLE
!               AND AT SUN (=0) OR QUADRATURE (>0) ANGLE.
      LOGICAL LAMBER
      REAL TPTEMP,TPHDIR,TPBRDF,AATEMP,AASALB,AADREF,EMU,BEM,RMU,BDR
      COMMON/SURFWV/LAMBER,TPTEMP(MLOS),TPHDIR(MLOS),TPBRDF(MLOS),      &
     &  AATEMP,AASALB,AADREF,EMU(MXUMU),BEM(MI),                        &
     &  RMU(1:MXUMU,0:MI,0:MAZ),BDR(1:MI,0:MI,0:MAZ)                    &

!     /JM1A1/
!       RESCHR   BAND MODEL RESOLUTION CHARACTER STRING.
!       DISSTR   CHARACTER STRING USED TO READ IN DISORT LOGICALS.
!       H2OSTR   VERTICAL WATER COLUMN CHARACTER STRING (IF THE
!                FIRST NON-BLANK CHARACTER IS A "G", THE WATER
!                COLUMN IN GM/CM2 FOLLOWS "G"; IF THE FIRST
!                NON-BLANK CHARACTER IS AN "A", THE WATER COLUMN
!                IN ATM-CM AT 273.15K FOLLOWS "A"; OTHERWISE THE
!                STRING CONTAINS A WATER COLUMN SCALING FACTOR).
!       O3STR    VERTICAL OZONE COLUMN CHARACTER STRING (IF THE
!                FIRST NON-BLANK CHARACTER IS A "G", THE OZONE
!                COLUMN IN GM/CM2 FOLLOWS "G"; IF THE FIRST
!                NON-BLANK CHARACTER IS AN "A", THE OZONE COLUMN
!                IN ATM-CM AT 273.15K FOLLOWS "A"; OTHERWISE THE
!                STRING CONTAINS AN OZONE COLUMN SCALING FACTOR).
!       USRSUN   USER-SPECIFIED TOP-OF-ATMOSPHERE SOLAR IRRADIANCE FILE.
!       BMROOT   PREFIX OF MOLECULAR BAND MODEL PARAMETERS FILE.
!       FILTNM   NAME OF FILTER RESPONSE FUNCTION FILE.
!       H2OAER   FLAG, TRUE IF DEFAULT AEROSOL PROPERTIES ARE REVISED
!                BASED ON WATER COLUMN SCALING.
!       DATDIR   NAME OF THE MODTRAN DATA DIRECTORY.
      CHARACTER RESCHR*2,DISSTR*3,H2OSTR*10,O3STR*10,USRSUN*(NAMLEN),   &
     &  FILTNM*(NAMLEN),BMROOT*(NAMLEN),H2OAER*1,DATDIR*(NAMLEN-LENSUN)
      COMMON/JM1A1/RESCHR,DISSTR,H2OSTR,O3STR,USRSUN,                   &
     &  FILTNM,BMROOT,H2OAER,DATDIR

!     /DISRT/
!       UMU      MONOTONICALLY INCREASING LIST OF DISTINCT USER-PATH
!                COSINE POLAR ANGLES.
!       PHI      MONOTONICALLY INCREASING LIST OF DISTINCT RELATIVE
!                SOLAR AZIMUTH ANGLES [0 TO 180 DEG].
!       NSTR     NUMBER OF DISCRETE ORDINATE STREAMS.
!       NAZ      NUMBER OF DISORT AZIMUTH COMPONENTS.
!       N2GAUS   ORDER OF DOUBLE-GAUSS QUADRATURES.
!       NUMU     NUMBER OF DISTINCT USER LINE-OF-SIGHT POLAR ANGLES.
!       MAPUMU   MAPPING FROM LINE-OF-SIGHT INDEX TO UMU ARRAY ENTRY.
!       NPHI     NUMBER OF DISTINCT RELATIVE SOLAR AZIMUTH ANGLES.
!       MAPPHI   MAPPING FROM LINE-OF-SIGHT INDEX TO PHI ARRAY ENTRY.
!       DIS      LOGICAL FLAG, TRUE FOR DISORT MULTIPLE SCATTERING.
!       DISAZM   LOGICAL FLAG, TRUE FOR DISORT WITH AZIMUTH DEPENDENCE.
!       DISALB   LOGICAL FLAG, TRUE FOR DISORT SPHERICAL ALBEDO OPTION.
!       LDISCL   LOGICAL FLAG, TRUE FOR ISAACS SCALED TO DISORT.
      REAL UMU,PHI
      INTEGER NSTR,NAZ,N2GAUS,NUMU,MAPUMU,NPHI,MAPPHI
      LOGICAL DIS,DISAZM,DISALB,LDISCL
      COMMON/DISRT/UMU(MXUMU),PHI(MAXPHI),NSTR,NAZ,N2GAUS,NUMU,         &
     &  MAPUMU(MLOS),NPHI,MAPPHI(MLOS),DIS,DISAZM,DISALB,LDISCL
      SAVE /DISRT/

!     /JM1A2/
!       SOLCON   SOLAR CONSTANT (ACTUAL VALUE IF POSITIVE,
!                                SCALE FACTOR IF NEGATIVE).
      LOGICAL LSUN
      REAL SFWHM,CO2MX,SOLCON
      COMMON/JM1A2/LSUN,SFWHM,CO2MX,SOLCON

!     /JM2/
      CHARACTER APLUS*2,CNOVAM*1,ARUSS*3
      COMMON/JM2/APLUS,CNOVAM,ARUSS

!     /CARD2/
!       IHAZE    BOUNDARY LAYER AEROSOL MODEL NUMBER.
!       ISEASN   SEASON NUMBER (1=SPRING-SUMMER, 2=FALL-WINTER).
!       IVULCN   VOLCANIC AEROSOL MODEL NUMBER.
!       ICSTL    COASTAL AIRMASS MODEL NUMBER.
!       ICLD     CLOUD MODEL NUMBER.
!       IVSA     VERTICAL STRUCTURE ALGORITHM (0=OFF, 1=ON).
!       VIS      SURFACE VISIBILITY (GROUND METEOROLOGICAL RANGE) [KM].
!       WSS      CURRENT WIND SPEED (M/S).
!       WHH      24-HOUR WIND SPEED (M/S).
!       RAINRT   RAIN RATE (MM/HR)
!       LSAP     LOGICAL FLAG FOR SPECTRAL AEROSOL PROFILES INPUT.
      INTEGER IHAZE,ISEASN,IVULCN,ICSTL,ICLD,IVSA
      REAL VIS,WSS,WHH,RAINRT
      LOGICAL LSAP
      COMMON/CARD2/IHAZE,ISEASN,IVULCN,ICSTL,ICLD,IVSA,                 &
     &  VIS,WSS,WHH,RAINRT,LSAP

!     /GRND/
!       GNDALT   GROUND ALTITUDE, ABOVE SEA LEVEL [KM].
      DOUBLE PRECISION GNDALT
      COMMON/GRND/GNDALT

!     /JM2APLUS/
      DOUBLE PRECISION ZAER11,ZAER12,ZAER21,ZAER22,                     &
     &  ZAER31,ZAER32,ZAER41,ZAER42
      REAL SCALE1,SCALE2,SCALE3,SCALE4
      COMMON/JM2APLUS/ZAER11,ZAER12,ZAER21,ZAER22,ZAER31,ZAER32,        &
     &  ZAER41,ZAER42,SCALE1,SCALE2,SCALE3,SCALE4

!     /CARD2A/
      INTEGER NCRALT,NCRSPC
      DOUBLE PRECISION CTHIK,CALT
      REAL CEXT,CWAVLN,CCOLWD,CCOLIP,CHUMID,ASYMWD,ASYMIP
      COMMON/CARD2A/CTHIK,CALT,CEXT,NCRALT,NCRSPC,CWAVLN,CCOLWD,        &
     &  CCOLIP,CHUMID,ASYMWD,ASYMIP

!     /CARD2B/
      REAL ZCVSA,ZTVSA,ZINVSA
      COMMON/CARD2B/ZCVSA,ZTVSA,ZINVSA

!     /TITL/
      CHARACTER HHAZE(16)*20,HSEASN(2)*20,HVULCN(8)*20,                 &
     &  HMET(2)*20,HMODEL(0:8)*20
      COMMON/TITL/HHAZE,HSEASN,HVULCN,HMET,HMODEL

!     /MPROF/
!       ZM       PROFILE LEVEL ALTITUDES [KM].
!       PM       PROFILE LEVEL PRESSURES [MBAR].
!       TM       PROFILE LEVEL TEMPERATURES [K].
!       RFNDX    PROFILE LEVEL REFRACTIVITIES.
!       LRHSET   FLAG, .TRUE. IF RELATIVE HUMIDITY IS NOT TO BE SCALED.
      DOUBLE PRECISION ZM
      REAL PM,TM,RFNDX
      LOGICAL LRHSET
      COMMON/MPROF/ZM(LAYDIM),PM(LAYDIM),TM(LAYDIM),                    &
     &  RFNDX(LAYDIM),LRHSET(LAYDIM)

!     /M_PTWO/
!       PPROF    PRESSURE PROFILE [MB].
!       TPROF    TEMPERATURE PROFILE [K].
!       WH2O     H2O VOLUME MIXING RATIO PROFILE [PPMV].
!       WO3      O3 VOLUME MIXING RATIO PROFILE [PPMV].
      REAL PPROF,TPROF,WH2O,WO3
      COMMON/M_PTWO/PPROF(LAYDIM),TPROF(LAYDIM),WH2O(LAYDIM),WO3(LAYDIM)

!     /CARD1B/
      INTEGER JUNITP,JUNITT,JUNIT,JLOW
      REAL WMOL
      COMMON/CARD1B/JUNITP,JUNITT,JUNIT(13),WMOL(12),JLOW

!     /JM1B/
      CHARACTER JCHAR*17
      COMMON/JM1B/JCHAR

!     /CD1BXY/
!       JUNITX   INPUT UNIT FLAG FOR CROSS-SECTION MOLECULES.
!       WMOLX    X-SECTION MOLECULAR DENSITY [PPMV AFTER JUBRAN CALL].
!       JUNITY   INPUT UNIT FLAG FOR AUXILIARY (Y) MOLECULES.
!       WMOLY    AUXILIARY MOLECULAR DENSITY [PPMV AFTER JUBRAN CALL].
      INTEGER JUNITX,JUNITY
      REAL WMOLX,WMOLY
      COMMON/CD1BXY/JUNITX,WMOLX(NMOLX),JUNITY,WMOLY(MMOLY)

!     /CARD2D/
      INTEGER IREG,IREGC
      DOUBLE PRECISION ALTB
      COMMON/CARD2D/IREG(4),ALTB(4),IREGC(4)

!     /USSPC/
      LOGICAL LARUSS
      INTEGER NARSPC
      REAL VARSPC
      COMMON/USSPC/NARSPC(4),VARSPC(4,NWAVLN),LARUSS

!     /JM2C3/
      REAL AHAZE(4),EQLWCZ,RRATZ
      INTEGER IHA1,ICLD1,IVUL1,ISEA1,ICHR
      COMMON/JM2C3/AHAZE,EQLWCZ,RRATZ,IHA1,ICLD1,                       &
     &   IVUL1,ISEA1,ICHR

!     /CLDRR/
!       ZCLD     INPUT (*,0) & MODEL (*,1) CLOUD ALTITUDE PROFILES [KM].
!       PCLD     CLOUD PROFILE PRESSURE [MB].
!       CLD      INPUT (*,0) & MODEL (*,>0) WATER CLOUD PROFILES [G/M3].
!       CLDICE   INPUT (*,0) & MODEL (*,>0) ICE CLOUD PROFILES [G/M3].
!       RR       INPUT (*,0) & MODEL (*,>0) RAIN RATE PROFILES [MM/HR].
      DOUBLE PRECISION ZCLD
      REAL PCLD,CLD,CLDICE,RR
      COMMON/CLDRR/ZCLD(1:NZCLD,0:1),PCLD,CLD(1:NZCLD,0:5),             &
     &  CLDICE(1:NZCLD,0:1),RR(1:NZCLD,0:5)

!     /CARD3/
!       H1ALT    OBSERVER (SENSOR) ALTITUDE [KM].
!       H2ALT    FINAL (TANGENT FOR LIMB PATH) ALTITUDE [KM].
!       OBSZEN   OBSERVER ZENITH ANGLE (H1ALT TO H2ALT) [DEG].
!       HRANGE   DISTANCE FROM H1ALT TO H2ALT [KM].
!       BETA     EARTH CENTER ANGLE BETWEEN H1ALT AND H2ALT [DEG].
!       REARTH   RADIUS OF THE EARTH [KM].
!       HMIN     PATH MINIMUM ALTITUDE [KM].
!       HMAX     PATH MAXIMUM ALTITUDE [KM].
!       CKRANG   MAXIMUM PATH RANGE FOR K-DISTRIBUTION OUTPUT
!                (=0. FOR TOTAL PATH ONLY; <0. FOR ALL RANGES).
!       BCKZEN   ZENITH ANGLE FOR BACKWARD (H2ALT TO H1ALT) PATH [DEG].
!       REARTH   EARTH RADIUS [KM].
!       ANGLEM   LUNAR PHASE ANGLE [0 TO 180 DEG].
!       LENN     PATH LENGTH SWITCH (0=SHORT, 1=LONG).
!       IDAY     DAY OF YEAR [0-366, DEFAULT (0) IS DAY 91].
!       ISOURC   SOURCE FLAG [0=SUN AND 1=MOON].
!       NLOS     NUMBER OF LINE-OF-SIGHT PATHS.
      INTEGER LENN,IDAY,ISOURC,NLOS
      DOUBLE PRECISION H1ALT,H2ALT,OBSZEN,HRANGE,BETA,REARTH,           &
     &  HMIN,HMAX,CKRANG,BCKZEN,ANGLEM
      COMMON/CARD3/H1ALT(MLOS),H2ALT(MLOS),OBSZEN(MLOS),HRANGE(MLOS),   &
     &  BETA(MLOS),HMIN(MLOS),HMAX(MLOS),CKRANG(MLOS),BCKZEN(MLOS),     &
     &  REARTH,ANGLEM,LENN(MLOS),IDAY,ISOURC,NLOS

!     /JM3A1/
      INTEGER IPARM
      COMMON/JM3A1/IPARM

!     /CARD3A/
      INTEGER IPH
      REAL G
      COMMON/CARD3A/IPH,G

!     /JM3A2/
!       IPRMSV   SAVED VALUE OF IPARM INPUT.
!       PARM1    SENSOR LATITUDE IF IPARM=0 OR =1 [DEG N OF EQUATOR].
!                TARGET LATITUDE IF IPARM=10 OR =11 [DEG N OF EQUATOR].
!                SOLAR REL AZIMUTH AT SENSOR IF IPARM=2 [DEG E OF N].
!                SOLAR REL AZIMUTH AT TARGET IF IPARM=12 [DEG E OF N].
!       PARM2    SENSOR LONGITUDE IF IPARM=0 OR =1 [DEG W OF GRNWCH].
!                TARGET LONGITUDE IF IPARM=10 OR =11 [DEG W OF GRNWCH].
!                SOLAR ZENITH AT SENSOR IF IPARM IS 2 [DEG].
!                SOLAR ZENITH AT TARGET IF IPARM IS 12 [DEG].
!       SRCLAT   SOURCE (SUN OR MOON) LATITUDE [DEG NORTH OF EQUATOR].
!       SRCLON   SOURCE (SUN OR MOON) LONGITUDE [DEG WEST OF GREENWICH].
!       GMTIME   GREENWICH MEAN TIME [DECIMAL HOURS].
!       TRUEAZ   PATH TRUE AZIMUTH ANGLE [DEG EAST OF NORTH].
      INTEGER IPRMSV
      DOUBLE PRECISION PARM1,PARM2,SRCLAT,SRCLON,GMTIME,TRUEAZ
      COMMON/JM3A2/PARM1,PARM2,SRCLAT,SRCLON,GMTIME,TRUEAZ,IPRMSV

!     /USRDTA/
      INTEGER NAERF,NWLF
      REAL WLF,F
      COMMON/USRDTA/NAERF,NWLF,WLF(MWLF),F(MAERF,MANGLS,MWLF)

!     /SCAN/
!       V1       LOWER BOUND ON SPECTRAL RANGE [CHUNIT DEFINES UNIT].
!       V2       UPPER BOUND ON SPECTRAL RANGE [CHUNIT DEFINES UNIT].
!       DV       SPECTRAL STEP SIZE FOR OUTPUT [CHUNIT DEFINES UNIT].
!       FWHM     FULL-WIDTH-AT-HALF-MAXIMUM [CHUNIT DEFINES UNIT].
!       FWHMSQ   TRIANGULAR SLIT NORMALIZATION FACTOR
!                (EQUALS FWHM SQUARED) [CHUNIT DEFINES UNIT].
!       VOUT     CURRENT SPECTRAL OUTPUT [CHUNIT DEFINES UNIT].
!       M2_FAC   FACTOR IN 2ND MOMENT DIFFERENCE INTEGRAL [CHUNIT UNIT].
      DOUBLE PRECISION V1,V2,DV,VOUT,FWHMSQ
      REAL FWHM,M2_FAC
      COMMON/SCANFN/V1,V2,DV,VOUT,FWHMSQ,FWHM,M2_FAC

!     COMMON /CFLAGS/
!       YFLAG    Y COORDINATE FLAG FOR plot.dat FILE
!                  = "T" FOR TRANSMITTANCE
!                  = "R" FOR RADIANCE (IRRADIANCE FOR IEMSCT=3)
!                  = "N" FOR NO plot.dat OUTPUT
!       XFLAG    X COORDINATE FLAG FOR plot.dat FILE
!                  = "W" FOR FREQUENCY IN WAVENUMBERS (CM-1) AND
!                        RADIANCE IN W SR-1 CM-2 / CM-1
!                  = "M" FOR WAVELENGTH IN MICRONS AND
!                        RADIANCE IN W SR-1 CM-2 / MICRON
!                  = "N" FOR WAVELENGTH IN NANOMETERS AND
!                        RADIANCE IN MICRO-WATTS SR-1 CM-2 / NANOMETER
!       DLIMIT   DELIMITER CHARACTER STRING BETWEEN MODTRAN RUNS
!       FLAGS    SCANNING FUNCTION FLAGS.
      CHARACTER YFLAG*1,XFLAG*1,DLIMIT*8,FLAGS*7
      COMMON/CFLAGS/YFLAG,XFLAG,DLIMIT,FLAGS

!     /JM4A/
!       NSURF   NUMBER OF SURFACES (1 IF IMAGED PIXEL AND AREA-AVERAGED
      INTEGER NSURF
      COMMON/JM4A/NSURF

!     /JM4L1/
!       SALBFL  SPECTRAL ALBEDO FILE NAME FOR LAMBERTIAN SURFACE.
      CHARACTER SALBFL*(NAMLEN)
      COMMON/JM4L1/SALBFL

!     /JM4L2/
!       CSALB   LAMBERTIAN SURFACE IDENTIFIER, INTEGER LABEL OR NAME.
      CHARACTER CSALB*80
      COMMON/JM4L2/CSALB

!     /JM4B1/
!       CBRDF   BRDF IDENTIFIER, INTEGER LABEL OR NAME.
      CHARACTER CBRDF*80
      COMMON/JM4B1/CBRDF

!     /SRFACE/
!       NWVSRF   NUMBER OF WAVELENGTH GRID POINTS.
!       WVSURF   WAVELENGTH GRID FOR IMAGED-PIXELS (1 TO MLOS) AND
!                AREA-AVERAGED (MLOSP1) SURFACES [MICRONS].
!       GDIRRF   AREA-AVERAGED GROUND SURFACE DIRECTIONAL REFLECTIVITY
!                AT SOLAR ANGLE.
!       SALB     AREA-AVERAGED GROUND SURFACE ALBEDO SPECTRAL ARRAY.
!       GAZMOM   GAUSS ANGLE AREA-AVG'D BRDF AZIMUTH FOURIER MOMENTS.
!       VAZMOM   VIEW ANGLE AREA-AVG'D BRDF AZIMUTH FOURIER MOMENTS.
!       GDIREM   GAUSS ANGLE AREA-AVG'D GROUND DIRECTIONAL EMISSIVITIES.
!       VDIREM   VIEW ANGLE AREA-AVG'D GROUND DIRECTIONAL EMISSIVITIES.
!       HDIR     IMAGED-PIXEL HEMISPHERE DIRECTIONAL REFLECTANCES
!                AT VIEWING ANGLES.
!       BRDF     IMAGED-PIXEL BIDIRECTIONAL REFLECTANCE DISTRIBUTION
!                FUNCTION AT VIEWING, SUN AND RELATIVE AZIMUTH ANGLES.
      INTEGER NWVSRF
      REAL WVSURF,GDIRRF,SALB,GAZMOM,VAZMOM,GDIREM,VDIREM,HDIR,BRDF
      COMMON/SRFACE/NWVSRF(MLOSP1),WVSURF(MLOSP1,MWVSRF),               &
     &  GDIRRF(MWVSRF),SALB(MWVSRF),GAZMOM(1:MI,0:MI,0:MAZ,1:MWVSRF),   &
     &  VAZMOM(1:MLOS,0:MI,0:MAZ,1:MWVSRF),GDIREM(MI,MWVSRF),           &
     &  VDIREM(MLOS,MWVSRF),HDIR(MLOS,MWVSRF),BRDF(MLOS,MWVSRF)

!     /JM4B2/
!       SURFZN  ZENITH ANGLE OF SURFACE NORMAL [DEG].
!       SURFAZ  SURFACE NORMAL TO VIEW DIRECTION RELATIVE
!               AZIMUTH ANGLE DEFINED AT THE SURFACE [DEG].
      REAL SURFZN,SURFAZ
      COMMON/JM4B2/SURFZN,SURFAZ

!     /JM4B3/
!       PARAMS  PARAMETERS IN BRDF REPRESENTATION.
      REAL PARAMS
      COMMON/JM4B3/PARAMS(MBRDF)

!     /JM5/
!       IRPT     REPEAT INPUT FLAG (0=NONE, 1=ALL, 3=GEOM, 4=SPEC).
!       IFAC     CURRENT COLUMN SCALING FACTOR INDEX.
!       NFACMN   NUMBER OF COLUMN SCALING FACTOR LESS THAN 1.
!       NFACMX   NUMBER OF COLUMN SCALING FACTOR GREATER THAN 1.
!       FACMC    CURRENT COLUMN SCALING FACTOR.
!       SCALMN   MINIMUM COLUMN SCALING FACTOR.
!       SCALMX   MAXIMUM COLUMN SCALING FACTOR.
!       LBMRES   LOGICAL FLAG, .TRUE. FOR BAND MODEL AND .FALSE.
!                FOR 1 NM SPECTRAL RESOLUTION OUTPUT.
      INTEGER IRPT,IFAC,NFACMN,NFACMX
      REAL FACMC
      DOUBLE PRECISION SCALMN,SCALMX
      LOGICAL LBMRES
      COMMON/JM5/SCALMN,SCALMX,IRPT,IFAC,NFACMN,NFACMX,FACMC,LBMRES

!     /CJM5/
!       AMOD3D   FLAG INDICATING OUTPUT DATABASE FILE TYPE:
      CHARACTER AMOD3D*1
      COMMON/CJM5/AMOD3D

!     SAVED COMMONS:
      SAVE /TITL/,/CLDRR/

!     FUNCTIONS:
!       LENSTR   RETURNS STRING LENGTH AFTER TRIMMING LEADING BLANKS.
      INTEGER LENSTR

!     LOCAL VARIABLES:
!       LENDAT   LENGTH OF DATDIR CHARACTER STRING.
      INTEGER LENDAT

!     SAVED VARIABLES:
!       K        ALTITUDE PROFILE INDEX.
!       IHC      AEROSOL REGION INDEX.
!       ICRALT   CLOUD/RAIN PROFILE INDEX.
!       ICRSPC   CLOUD/RAIN SPECTRAL INDEX.
!       IANGLS   AEROSOL SCATTERING PHASE FUNCTIONS ANGLE INDEX.
!       IWLF     AEROSOL SCATTERING PHASE FUNCTIONS WAVELENGTH INDEX.
!       ISURF    GROUND SURFACE TYPE
!                  (1 FOR IMAGED-PIXEL AND 2 FOR AREA-AVERAGE).
!       IWVSRF   SURFACE BRDF SPECTRAL INDEX.
      INTEGER K,IHC,ICRALT,ICRSPC,IANGLS,IWLF,ISURF,IWVSRF
      SAVE K,IHC,ICRALT,ICRSPC,IANGLS,IWLF,ISURF,IWVSRF

!     DATA:
!       IATM     COUNTER FOR NUMBER OF ATMOSPHERE CALCULATIONS.
!bug    FRMT     CHARACTER STRING INPUT FORMAT.
      INTEGER IATM
!bug  CHARACTER FRMT*9
!bug  SAVE IATM,FRMT
!bug  DATA IATM/0/,FRMT/'((A    ))'/
      SAVE IATM
      DATA IATM/0/


!     BRANCH BASED ON ROUTINE ARGUMENT:
      IF(CHARIN.EQ.'CARD1')THEN

!         CARD1:
!         READ(IRD,'(2A1,I3,12I5,F8.3,A7)')                             &
!    &      CODE,SPEED,MODEL,ITYPE,IEMSCT,IMULT,                        &
!    &      M1,M2,M3,M4,M5,M6,MDEF,I_RD2C,NOPRNT,TPTEMP,SURREF

!         MODTRAN BAND MODEL WITH CORRELATED-K OPTION [CODE='C']
!         MODERATE SPEED CORRELATED-K OPTION [SPEED='M']
!         PRESSURE DEPENDENT RADIOSONDE DATA WITH US STANDARD
!         ATMOSPHERIC DEFAULT PROFILES
!           [MODEL=8,M1=6,M2=6,M3=6,M4=6,M5=6,M6=6,MDEF=1,I_RD2C=1]
!         SLANT PATH TO SPACE (OR GROUND) [ITYPE=3]
!         THERMAL EMITTED RADIANCE ONLY [IEMSCT=1]
!         NO MULTIPLE SCATTERING [IMULT=0]
!         MINIMAL WRITE OUTPUT [NOPRNT=1]
!         NO EMISSIVE IMAGED AT FINAL ALTITUDE [TPTEMP=-1.]
!         BLACKBODY GROUND SURFACE [SURREF=' 0.0000']
          CODE='C'
          SPEED='M'
          MODEL=8
          ITYPE=3
          IEMSCT=1
          IMULT=0
          M1=6
          M2=6
          M3=6
          M4=6
          M5=6
          M6=6
          MDEF=1
          I_RD2C=1
          NOPRNT=1
          TPTEMP(1)=0.
          SURREF=' 0.0000'
      ELSEIF(CHARIN.EQ.'CARD1A')THEN

!         CARD1A:
!         READ(IRD,'(A2,I3,L1,I4,F10.3,2A10,5(1X,A1),F10.3)')           &
!    &      DISSTR,NSTR,LSUN,SFWHM,CO2MX,H2OSTR,O3STR,USRSUN(1:1),      &
!    &      BMROOT(1:1),FILTNM(1:1),H2OAER,DATDIR(1:1),SOLCON

!         ISAACS 2-STREAM MULTIPLE SCATTERING [DISSTR='FTT']
!         DEFAULT TOP-OF-ATMOSPHERE SOLAR SPECTRAL IRRADIANCES
!           [LSUN=.FALSE.,SFWHM=5]
!         LOOP OVER CO2, H2O AND O3 SCALING FACTORS FOR MOD3D:
!         NO ADJUSTMENT OF THE SOLAR CONSTANT [SOLCON=0.]
!         15 CM-1 BAND MODEL.
          DISSTR='FTT'
          NSTR=16
          LSUN=.FALSE.
          SFWHM=5.
          IF(MOD(IATM,4).LE.1)THEN
              CO2MX=400.
          ELSE
              CO2MX=320.
          ENDIF
          IF(IATM.GE.4*NH2O)THEN

!             NO H2O LIMIT:
              H2OSTR='g0.0000000'
          ELSE
              H2OSTR(1:1)='+'
              WRITE(H2OSTR(2:10),'(F9.7)')2*(1.-FLOAT(IATM/4)/NH2O)
!bug          WRITE(H2OSTR,'(F10.7)')1.-FLOAT(IATM/4)/NH2O
          ENDIF
          IF(MOD(IATM,2).EQ.0)THEN
              O3STR='   2.00000'
          ELSE
              O3STR='   0.50000'
          ENDIF
          H2OAER='F'
          DATDIR='DATA/'
          SOLCON=0.

!         CARD1A1:
!bug      WRITE(FRMT(4:7),'(I4.4)')NAMLEN
!         READ(IRD,FRMT)USRSUN

!         DEFAULT ('DATA/SUN01kurucz2005.dat') SOLAR IRRAD. [USRSUN=blank]
          USRSUN='                                        '//           &
     &           '                                        '

!         CARD1A2:
!         READ(IRD,FRMT)BMROOT

!         DEFAULT ('DATA/BMP98_01.BIN') 1CM-1 BAND
!         MODEL DATA [BMROOT=blank]
          LENDAT=LENSTR(DATDIR)
          BMROOT=DATDIR(1:LENDAT)//'BMP99_15.BIN'

!         CARD1A3:
!         READ(IRD,FRMT)FILTNM

!         NO INSTRUMENT FILTER (CHANNEL) RESPONSE
!         FUNCTION [FILTNM=blank]
          FILTNM=' '
      ELSEIF(CHARIN.EQ.'CARD2')THEN

!         CARD2:
!         READ(IRD,'(A2,I3,A1,I4,A3,I2,3I5,5F10.5)')
!    1      APLUS,IHAZE,CNOVAM,ISEASN,ARUSS,
!    2      IVULCN,ICSTL,ICLD,IVSA,VIS,WSS,WHH,RAINRT,GNDALT

!         NO TAILORING OF AEROSOL OPTICAL PROPERTIES OR PROFILES
!           [APLUS='  ',ARUSS='   ']
!         NOVAM (NAVY OCEANIC VERTICAL AEROSOL MODEL) NOT USED
!           [CNOVAM=' ']
!         RURAL AEROSOL MODEL WITH 23KM SURFACE METEOROLOGICAL RANGE
!           [IHAZE=1,VIS=23.]
!         SPRING-SUMMER TROPOSPHERIC AND STRATOSPHERIC AEROSOLS
!           [ISEASN=1]
!         BACKGROUND STRATOSPHERIC PROFILE AND EXTINCTION [IVULCN=1]
!         DEFAULT AIR MASS CHARACTER FOR NAVY AEROSOL MODEL [ICSTL=3]
!         CUMULUS CLOUD TYPE [ICLD=1]
!         ARMY VERTICAL STRUCTURE ALGORITHM NOT USED [IVSA=0]
!         DEFAULT CURRENT AND 24-HOUR WIND SPEEDS [WSS=0.,WHH=0.]
!         NO CONSTANT RAIN PROFILE [RAINRT=0.]
!         GROUND ALTITUDE AT 0. KM ABOVE SEA LEVEL [GNDALT=0.]
          APLUS='  '
          IHAZE=1
          CNOVAM=' '
          ISEASN=1
          ARUSS='   '
          IVULCN=1
          ICSTL=3
          ICLD=1
          IVSA=0
          VIS=23.
          WSS=0.
          WHH=0.
          RAINRT=0.
          GNDALT=0.D0
      ELSEIF(CHARIN.EQ.'CARD2APLUS')THEN

!         CARD2A+:
!         READ(IRD,'((3(1X,F9.0),20X,3(1X,F9.0)))')
!    1      ZAER11,ZAER12,SCALE1,ZAER21,ZAER22,SCALE2,
!    2      ZAER31,ZAER32,SCALE3,ZAER41,ZAER42,SCALE4

!         RETAIN DEFAULT AEROSOL PROFILES
!           [ZAER11= 0.,ZAER12=  3.,SCALE1=1.,
!            ZAER21= 2.,ZAER22= 11.,SCALE2=1.,
!            ZAER31=10.,ZAER32= 35.,SCALE3=1.,
!            ZAER41=30.,ZAER42=100.,SCALE4=1.]
          ZAER11=0.D0
          ZAER12=3.D0
          SCALE1=1.
          ZAER21=2.D0
          ZAER22=11.D0
          SCALE2=1.
          ZAER31=10.D0
          ZAER32=35.D0
          SCALE3=1.
          ZAER41=30.D0
          ZAER42=100.D0
          SCALE4=1.
      ELSEIF(CHARIN.EQ.'CARD2A')THEN

!         CARD2A:
!         READ(IRD,'(3F8.3,2I4,6F8.3)')CTHIK,CALT,CEXT,NCRALT,
!    1      NCRSPC,CWAVLN,CCOLWD,CCOLIP,CHUMID,ASYMWD,ASYMIP

!         DEFAULT CLOUD OPTICAL PROPERTIES [-9's].
!         THREE LEVEL CLOUD/RAIN PROFILE [NCRALT=3].
!         RELATIVE HUMIDITY IN EXCESS OF 105% AS A FLAG TO INDICATE
!           NO MODIFICATION OF THE H2O VAPOR PROFILE WITHIN CLOUDS.
          CTHIK=-9.D0
          CALT=-9.D0
          CEXT=-9.
          NCRALT=3
          NCRSPC=-9
          CCOLWD=-9.
          CCOLIP=-9.
          CHUMID=200.
          ASYMWD=-9.
          ASYMIP=-9.
          ICRALT=0
          ICRSPC=0
      ELSEIF(CHARIN.EQ.'CARD2B')THEN

!         CARD2B:
!         READ(IRD,'(3F10.5)')ZCVSA,ZTVSA,ZINVSA

!         USE DEFAULT ARMY VERTICAL STRUCTURE ALGORITHM DATA
          ZCVSA=0.
          ZTVSA=0.
          ZINVSA=0.
      ELSEIF(CHARIN.EQ.'CARD2C')THEN

!         CARD2C:
!         READ(IRD,'(3I5,A20,F10.0)')ML,IRD1,IRD2,HMODEL(7),REARTH

!         51 PROFILE LEVELS (50 ATMOSPHERIC LAYERS) [ML=51].
!         DEFAULT PROFILES FOR ALL SPECIES OTHER THAN
!           H2O, CO2 AND O3 [IRD1=0 AND IRD2=0].
!         PROFILES AND TO USE DEFAULT AEROSOL PROFILES.
!         INITIALIZE THE ATMOSPHERIC LEVEL INDEX TO 0.
          ML=51
          IRD1=0
          IRD2=0
          HMODEL(7)='BUILD MOD3D DATABASE'
          K=0
          REARTH=6371.23D0
      ELSEIF(CHARIN.EQ.'CARD2C1')THEN

!         CARD2C1:
!         READ(IRD,'(F10.0,5E10.3,A17)')
!    1      ZM(K),PPROF(K),TPROF(K),WMOL(1),WMOL(2),WMOL(3),JCHAR

!         UNIFORM PRESSURE GRID FROM PBOT TO PTOP (SEE PARAMETERS
!           ABOVE) IN MBARS.
!         LET MODTRAN SOLVE FOR ALTITUDES USING THE HYDROSTATIC
!           EQUATION AND THE INPUT GROUND ALTITUDE (CARD2).
!         LET TEMPERATURE, CO2 AND O3 PROFILES REVERT BACK TO U.S.
!           STANDARD ATMOSPHERE VALUES (FOR REAL SIMULATIONS, IT IS BEST
!           TO EXPLICITLY INPUT AN APPROPRIATE TEMPERATURE PROFILES).
!         A MAXIMUM H2O PROFILE IS REQUIRED FOR INTERPOLATION:
!           SET THE RELATIVE HUMIDITY (RH) TO 100% FOR PRESSURES
!           ABOVE 180 MBARS (APPROXIMATE LOCATION OF THE TROPOPAUSE).
!           SET RH TO P(MBARS) * 100%/ (1000 MBARS) FOR PRESSURES LESS
!           THAN 180 MBARS;  AT THE HIGHER ALTITUDES (LOWER PRESSURES)
!           RELATIVE HUMIDITY NEVER APPROACH 100%.
          K=K+1
          PPROF(K)=PBOT+(K-1)*(PTOP-PBOT)/(ML-1)
          TPROF(K)=0.
          IF(PPROF(K).GE.180.)THEN
              WMOL(1)=100.
          ELSE
              WMOL(1)=PPROF(K)/10
          ENDIF
          WMOL(2)=0.
          WMOL(3)=0.
          JCHAR='A H              '
      ELSEIF(CHARIN.EQ.'CARD2C2')THEN

!         CARD2C2:
!         READ(IRD,'((8F10.0))')(WMOL(I),I=4,12)

!         MOLECULAR DENSITIES FROM M1, M2, M3,
!         M4, M5, M6 AND MDEF VALUES OF CARD1.
          WMOL( 4)=0.
          WMOL( 5)=0.
          WMOL( 6)=0.
          WMOL( 7)=0.
          WMOL( 8)=0.
          WMOL( 9)=0.
          WMOL(10)=0.
          WMOL(11)=0.
          WMOL(12)=0.
      ELSEIF(CHARIN.EQ.'CARD2C2X')THEN

!         CARD2C2X:
!         READ(IRD,'((8F10.0))')(WMOLX(I),I=1,NMOLX)
!         ZERO OUT VALUES USING JCHARX [JCHAR(16:16)] EQUAL 'B',
!         I.E., DENSITIES IN MOLECULES/CM3.
          WMOLX( 1)=0.
          WMOLX( 2)=0.
          WMOLX( 3)=0.
          WMOLX( 4)=0.
          WMOLX( 5)=0.
          WMOLX( 6)=0.
          WMOLX( 7)=0.
          WMOLX( 8)=0.
          WMOLX( 9)=0.
          WMOLX(10)=0.
          WMOLX(11)=0.
          WMOLX(12)=0.
          WMOLX(13)=0.
          WMOLX(14)=0.
          WMOLX(15)=0.
      ELSEIF(CHARIN.EQ.'CARD2C3')THEN

!         CARD2C3:
!         READ(IRD,'(10X,3F10.0,5I5)')
!    1      AHAZE(1),EQLWCZ,RRATZ,IHA1,ICLD1,IVUL1,ISEA1,ICHR

!         PROFILE VALUES FOR IRD2=1 WITH 2KM SCALE HEIGHT.
          AHAZE(1)=EXP(-SNGL(ZM(K))/2)
          EQLWCZ=0.
          RRATZ=0.
          IHA1=IHAZE
          ICLD1=0
          IVUL1=0
          ISEA1=ISEASN
          IF(K.EQ.1)THEN
              ICHR=0
          ELSEIF(ZM(K-1).LE.2.5D0 .AND. ZM(K).GT.2.5D0)THEN
              ICHR=1
          ELSEIF(ZM(K-1).LE.10.5D0 .AND. ZM(K).GT.10.5D0)THEN
              ICHR=1
          ELSEIF(ZM(K-1).LE.32.5D0 .AND. ZM(K).GT.32.5D0)THEN
              ICHR=1
          ELSE
              ICHR=0
          ENDIF
      ELSEIF(CHARIN.EQ.'CARD2D')THEN

!         CARD2D:
!         READ(IRD,1200) (IREG(IK),IK=1,4)

!         READ IN SPECTRAL DATA FOR THE FIRST 2 AEROSOLS ONLY
          IREG(1)=3
          IREG(2)=4
          IREG(3)=0
          IREG(4)=0
          IHC=0
      ELSEIF(CHARIN.EQ.'CARD2D1')THEN

!         CARD2D1:
!         READ(IRD,'(E10.3,18A4)') AWCCON(IHC),TITLE

!         SET EXTINCTION COEFFICIENT TO EQUIVALENT LIQUID
!           WATER CONTENT CONVERSION FACTORS TO ZERO.
!         TITLE IS NOT USED FOR JMASS.
   10     CONTINUE
          IHC=IHC+1
          IF(IREG(IHC).LE.0)GOTO 10
          AWCCON(IHC)=0.

!         CARD2D2:
!         READ(IRD, '((3(F6.2,2F7.5,F6.4)))')(VARSPC(IHC,I),
!    1      EXTC(IHC,I), ABSC(IHC,I), ASYM(IHC,I),I=1, NARSPC(IHC))

!         DEFINE AEROSOL OPTICAL PROPERTIES FOR AEROSOLS 1 AND 2
          IF(IHC.EQ.1)THEN
              VARSPC(1,1)=0.50
              EXTC(1,1)  =0.95
              ABSC(1,1)  =0.03
              ASYM(1,1)  =0.80
              VARSPC(1,2)=0.55
              EXTC(1,2)  =1.00
              ABSC(1,2)  =0.03
              ASYM(1,2)  =0.80
              VARSPC(1,3)=0.60
              EXTC(1,3)  =0.98
              ABSC(1,3)  =0.03
              ASYM(1,3)  =0.80
          ELSEIF(IHC.EQ.2)THEN
              VARSPC(2,1)=0.50
              EXTC(2,1)  =0.95
              ABSC(2,1)  =0.03
              ASYM(2,1)  =0.85
              VARSPC(2,2)=0.55
              EXTC(2,2)  =1.00
              ABSC(2,2)  =0.03
              ASYM(2,2)  =0.85
              VARSPC(2,3)=0.58
              EXTC(2,3)  =1.03
              ABSC(2,3)  =0.03
              ASYM(2,3)  =0.85
              VARSPC(2,4)=0.60
              EXTC(2,4)  =0.97
              ABSC(2,4)  =0.03
              ASYM(2,4)  =0.85
          ELSEIF(IHC.EQ.3)THEN

          ELSEIF(IHC.EQ.4)THEN

          ENDIF
      ELSEIF(CHARIN.EQ.'CARD2E1')THEN

!         CARD2E1:
!         READ(IRD,'(4F10.0)',ERR=20)ZCLD(ICRALT,0),
!    1      CLD(ICRALT,0),CLDICE(ICRALT,0),RR(ICRALT,0)     (MODEL<8)
!         READ(IRD,'(4F10.0)',ERR=20)PCLD,
!    1      CLD(ICRALT,0),CLDICE(ICRALT,0),RR(ICRALT,0)     (MODEL=8)

!         WITH MODEL EQUAL 8, CLOUD PROFILE IS ENTERED IN PRESSURE
!           INSTEAD OF ALTITUDE.
!         TO DEFINE CLOUD AND RAIN PROPERTIES FOR MOD3D, THE PROFILE
!           IS DEFINED FROM GROUND TO THE TOP-OF-ATMOSPHERE.
!         THE ACTUAL VALUE OF THE CLOUD AND RAIN AMOUNTS ARE
!           FACTORED OUT OF THE MOD3D SPECTRAL DATABASE, BUT MUST
!           BE POSITIVE.  HERE THE CLOUD/RAIN AMOUNTS ARE SET TO
!           0.5 GM/M3 WATER DROPLETS, 0.0 GM/M3 ICE PARTICLES, AND
!           10 MM/HR RAIN RATE.
          ICRALT=ICRALT+1
          IF(ICRALT.EQ.1)THEN
              PCLD            =PPROF(1)
              CLD(ICRALT,0)   =.5
              CLDICE(ICRALT,0)=.0
              RR(ICRALT,0)    =10.
          ELSEIF(ICRALT.EQ.2)THEN
              PCLD            =PPROF(ML-1)
              CLD(ICRALT,0)   =.5
              CLDICE(ICRALT,0)=.0
              RR(ICRALT,0)    =10.
          ELSEIF(ICRALT.EQ.3)THEN
              PCLD            =PPROF(ML)
              CLD(ICRALT,0)   =.0
              CLDICE(ICRALT,0)=.0
              RR(ICRALT,0)    =.0
          ENDIF
      ELSEIF(CHARIN.EQ.'CARD2E2')THEN

!         CARD2E2:
!         READ(IRD,'(7F10.0)',ERR=70)WAVLEN(I),
!    1      EXTC(6,I),ABSC(6,I),ASYM(6,I),EXTC(7,I),ABSC(7,I),ASYM(7,I)

!         DEFINE CLOUD AND RAIN OPTICAL PROPERTIES WITH NCRSPC=4
!         [USE MODEL VALUES FOR EXTINCTION AND SCATTERING PHASE
!         FUNCTION ASYMMETRY FACTOR - DEFINE ABSORPTION BY
!         SETTING THE SCATTERING COALBEDO (1-ALBEDO)].
          ICRSPC=ICRSPC+1
          IF(ICRSPC.EQ.1)THEN
              WAVLEN(ICRSPC)=.50
              EXTC(6,ICRSPC)=-9.
              ABSC(6,ICRSPC)=-.00001
              ASYM(6,ICRSPC)=-9.
              EXTC(7,ICRSPC)=-9.
              ABSC(7,ICRSPC)=-.00010
              ASYM(7,ICRSPC)=-9.
          ELSEIF(ICRSPC.EQ.2)THEN
              WAVLEN(ICRSPC)=.55
              EXTC(6,ICRSPC)=-9.
              ABSC(6,ICRSPC)=-.00003
              ASYM(6,ICRSPC)=-9.
              EXTC(7,ICRSPC)=-9.
              ABSC(7,ICRSPC)=-.00020
              ASYM(7,ICRSPC)=-9.
          ELSEIF(ICRSPC.EQ.3)THEN
              WAVLEN(ICRSPC)=.58
              EXTC(6,ICRSPC)=-9.
              ABSC(6,ICRSPC)=-.00003
              ASYM(6,ICRSPC)=-9.
              EXTC(7,ICRSPC)=-9.
              ABSC(7,ICRSPC)=-.00020
              ASYM(7,ICRSPC)=-9.
          ELSEIF(ICRSPC.EQ.4)THEN
              WAVLEN(ICRSPC)=.60
              EXTC(6,ICRSPC)=-9.
              ABSC(6,ICRSPC)=-.00001
              ASYM(6,ICRSPC)=-9.
              EXTC(7,ICRSPC)=-9.
              ABSC(7,ICRSPC)=-.00010
              ASYM(7,ICRSPC)=-9.
          ENDIF
      ELSEIF(CHARIN.EQ.'CARD3')THEN

!         CARD3:
!         READ(IRD,'(6F10.5,I5,5X,F10.5)')H1ALT(1),H2ALT(1),OBSZEN(1),
!    &      HRANGE(1),BETA(1),RO,LENN(1),BCKZEN(1)
!         ALTERNATE CARD3:
!         READ(IRD,'(2(3F10.5,I5,F15.5,I5))')
!    1      H1ALT(1),H2,OBSZEN(1),IDAY,RO,ISOURC,ANGLEM

!         SLANT PATH TO GROUND (ITYPE=3)
!         FOR MOD3D THE LINE-OF-SIGHT MUST BE DEFINED AS NADIR
!           VIEWING FROM TOP-OF-ATMOSPHERE OR ABOVE.
!         SET H1ALT TO THE MAXIMUM PROFILE ALTITUDE AND OBSZEN(1) TO 180
!           DEG.  ALL OTHER LINE-OF-SIGHT PARAMETERS ARE SET TO 0.
          H1ALT(1)=ZM(ML)
          H2ALT(1)=0.D0
          OBSZEN(1)=180.D0
          HRANGE(1)=0.D0
          BETA(1)=0.D0
          REARTH=0.D0
          LENN(1)=0
          BCKZEN(1)=0.D0
      ELSEIF(CHARIN.EQ.'CARD3A1')THEN

!     CARD3A1:
!         READ(IRD,'(4I5)')IPARM,IPH,IDAY,ISOURC

!         SPECIFY SOLAR/LUNAR POSITION USING EPHEMERAL DATA, AND
!         DEFINE RELATIVE SOLAR POSITION BY SPECIFYING SENSOR
!         (H1ALT) LAT/LONG.   SET DAY FOR MEAN SOLAR DISTANCE.  SET
!         SOURCE TO SUN.  USE MIE DATABASE FOR AEROSOL OPTICAL
!         PROPERTIES.
          IPARM=1
          IPH=2
          IDAY=93
          ISOURC=0
      ELSEIF(CHARIN.EQ.'CARD3A2')THEN

!         CARD3A2:
!         READ(IRD,'(8F10.5)')
!    1      PARM1,PARM2,SRCLAT,SRCLON,GMTIME,TRUEAZ,ANGLEM,G

!         PLACE SENSOR 0. LAT AND 0. LONG.  SET TIME TO NOON,
!         I.E., 0 LONG.  SET LUNAR PHASE ANGLE TO 0 (FULL MOON).
!         SET G TO 0.8 FOR FORWARD SCATTERING.  SET TRUEAZ TO 90
!         DEGREES FOR EASTWARD POINTING SENSOR.
          PARM1=0.D0
          PARM2=0.D0
          SRCLAT=0.D0
          SRCLON=0.D0
          GMTIME=12.D0
          TRUEAZ=90.D0
          ANGLEM=0.D0
          G=.8
      ELSEIF(CHARIN.EQ.'CARD3B1')THEN

!         CARD3B1:
!         READ(IRD,'(3(I5))')NANGLS,NWLF

!         USE 10 ANGLES AND 2 WAVELENGTHS.
          NANGLS=13
          NWLF=2
      ELSEIF(CHARIN.EQ.'CARD3B2')THEN

!         CARD3B2:
!         READ(IRD,'((5E10.3))')
!    1      (ANGF(I),F(1,I,1),F(2,I,1),F(3,I,1),F(4,I,1),I=1,NANGLS)

!         DEFINE GRID OF ANGLES BETWEEN 0 AND 180 DEGREES.
!         DEFINE NORMALIZED SCATTERING PHASE FUNCTIONS FOR THE
!         FOUR AEROSOLS.
          ANGF(1)=0.0
          ANGF(2)=0.1
          ANGF(3)=0.3
          ANGF(4)=0.7
          ANGF(5)=1.5
          ANGF(6)=3.0
          ANGF(7)=6.0
          ANGF(8)=12.0
          ANGF(9)=24.0
          ANGF(10)=45.0
          ANGF(11)=90.0
          ANGF(12)=135.0
          ANGF(13)=180.0
          DO 20 IANGLS=1,NANGLS
              F(1,IANGLS,1)=REC4PI
              F(2,IANGLS,1)=REC4PI
              F(3,IANGLS,1)=REC4PI
              F(4,IANGLS,1)=REC4PI
   20     CONTINUE
      ELSEIF(CHARIN.EQ.'CARD3C')THEN

!         CARD3Cn:
!         READ(IRD,'(8(1X,F9.0))')(ANGF(I),I=1,NANGLS)
!         READ(IRD,'(8(1X,F9.0))')(WLF(I),I=1,NWLF)
!         DO K=1,4
!             DO I=1,NANGLS
!                 READ(IRD,'(8(1X,E9.3))')(F(K,I,J),J=1,NWLF)
!             ENDDO
!         ENDDO

!         DEFINE GRID OF ANGLES BETWEEN 0 AND 180 DEGREES.
!         DEFINE NORMALIZED SPECTRAL SCATTERING PHASE FUNCTIONS FOR THE
!         FOUR AEROSOLS.
          ANGF(1)=0.0
          ANGF(2)=0.1
          ANGF(3)=0.3
          ANGF(4)=0.7
          ANGF(5)=1.5
          ANGF(6)=3.0
          ANGF(7)=6.0
          ANGF(8)=12.0
          ANGF(9)=24.0
          ANGF(10)=45.0
          ANGF(11)=90.0
          ANGF(12)=135.0
          ANGF(13)=180.0
          DO 40 IWLF=1,NWLF
              WLF(IWLF)=.50+(IWLF-1)*(.60-.50)/(NWLF-1)
              DO 30 IANGLS=1,NANGLS
                  F(1,IANGLS,IWLF)=REC4PI
                  F(2,IANGLS,IWLF)=REC4PI
                  F(3,IANGLS,IWLF)=REC4PI
                  F(4,IANGLS,IWLF)=REC4PI
   30         CONTINUE
   40     CONTINUE
      ELSEIF(CHARIN.EQ.'CARD4')THEN

!         CARD4:
!         READ(IRD,'(4F10.0,2A1,A8,A7)')
!    1      V1,V2,DV,FWHM,YFLAG,XFLAG,DLIMIT,FLAGS

!         SET SPECTRAL BANDPASS TO 2-25 MICRONS USING MULITPLES
!           OF 15 CM-1 [V1=390., V2=5010. CM-1]
!         SET THE OUTPUT STEP SIZE AND SPECTRAL RESOLUTION TO
!           THE BAND MODEL SPECTRAL WIDTH [DV=15.]
!         SET FLAGS TO MINIMIZE AUXILIARY OUTPUT
!           [YFLAG, XFLAG, DLIMIT, FLAGS = blank]
          V1=390.D0
          V2=5010.D0
          DV=15.D0
          FWHM=SNGL(DV)
          YFLAG=' '
          XFLAG=' '
          DLIMIT='        '
          FLAGS='       '
      ELSEIF(CHARIN.EQ.'CARD4A')THEN

!         CARD 4A:
!         READ(IRD,'(I1,F9.0)',IOSTAT=IOTEST)NSURF,AATEMP

!         DEFINE INDEPENDENT IMAGED-PIXEL AND AREA-AVERAGED
!         GROUND SURFACES.  SET AREA-AVERAGED TEMPERATURE TO
!         DEFAULT VALUE, I.E., TO TPTEMP IF LINE-OF-SIGHT
!         INTERSECTS THE EARTH OR TO THE FIRST (LOWEST ALTITUDE)
!         TEMPERATURE PROFILE VALUE.
          NSURF=2
          AATEMP=-1
      ELSEIF(CHARIN.EQ.'CARD4L1')THEN

!         CARD 4L1:
!bug      WRITE(FRMT(4:7),'(I4.4)')NAMLEN
!         READ(IRD,FRMT,IOSTAT=IOTEST)SALBFL

!         SET SPECTRAL ALBEDO FILE NAME TO DEFAULT SPECTRAL
!         ALBEDO FILE.  INITIALIZE SURFACE COUNTER.
          LENDAT=LENSTR(DATDIR)
          SALBFL=DATDIR(1:LENDAT)//'spec_alb.dat'
          ISURF=0
      ELSEIF(CHARIN.EQ.'CARD4L2')THEN

!         CARD 4L2:
!         READ(IRD,'(A80)')CSALB
          ISURF=ISURF+1
          IF(ISURF.EQ.1)THEN
              CSALB='MAPLE LEAF !SPECTRAL DATA FROM DATA/spec_alb.dat'
          ELSEIF(ISURF.EQ.2)THEN
              CSALB='BURNT GRASS !SPECTRAL DATA FROM DATA/spec_alb.dat'
          ENDIF
      ELSEIF(CHARIN.EQ.'CARD4B1')THEN

!         CARD 4B1:
!         READ(IRD,'(A80)')CBRDF

!         WALTHALL EMPIRICAL PARAMETERIZATION:
          ISURF=ISURF+1
          IF(ISURF.EQ.1)THEN
              CBRDF='Walthall'
          ELSEIF(ISURF.EQ.2)THEN
              CBRDF='Walthall'
          ENDIF
      ELSEIF(CHARIN.EQ.'CARD4B2')THEN

!         CARD 4B2:
!         READ(IRD,*,IOSTAT=IOTEST)NWVSRF(ISURF),SURFZN,SURFAZ

!         USE 4 SPECTRAL POINTS AND UPWARD SURFACE NORMAL:
          IF(ISURF.EQ.1)THEN
              NWVSRF(1)=4
              SURFZN=0.
              SURFAZ=0.
          ELSEIF(ISURF.EQ.2)THEN
              NWVSRF(MLOSP1)=4
              SURFZN=0.
              SURFAZ=0.
          ENDIF
          IWVSRF=0
      ELSEIF(CHARIN.EQ.'CARD4B3')THEN

!         CARD 4B3:
!         READ(IRD,*,IOSTAT=IOTEST)
!    1      WVSURF(ISURF,IWVSRF),(PARAMS(IPARAM),IPARAM=1,NPARAM)
          IWVSRF=IWVSRF+1
          IF(ISURF.EQ.1)THEN
              IF(IWVSRF.EQ.1)THEN
                  WVSURF(1,IWVSRF)=0.470
                  PARAMS(1)= 0.5586
                  PARAMS(2)= 0.0405
                  PARAMS(3)= 1.2828
                  PARAMS(4)=-0.7777
              ELSEIF(IWVSRF.EQ.2)THEN
                  WVSURF(1,IWVSRF)=0.555
                  PARAMS(1)= 0.6098
                  PARAMS(2)= 0.0562
                  PARAMS(3)= 1.3615
                  PARAMS(4)=-0.8180
              ELSEIF(IWVSRF.EQ.3)THEN
                  WVSURF(1,IWVSRF)=0.650
                  PARAMS(1)= 0.5696
                  PARAMS(2)= 0.0732
                  PARAMS(3)= 1.1296
                  PARAMS(4)=-0.6783
              ELSEIF(IWVSRF.EQ.4)THEN
                  WVSURF(1,IWVSRF)=0.827
                  PARAMS(1)= 0.5439
                  PARAMS(2)= 0.1248
                  PARAMS(3)= 0.9234
                  PARAMS(4)=-0.5080
              ENDIF
          ELSEIF(ISURF.EQ.2)THEN
              IF(IWVSRF.EQ.1)THEN
                  WVSURF(MLOSP1,IWVSRF)=0.470
                  PARAMS(1)= 0.0889
                  PARAMS(2)= 0.0000
                  PARAMS(3)= 0.0000
                  PARAMS(4)= 0.0000
              ELSEIF(IWVSRF.EQ.2)THEN
                  WVSURF(MLOSP1,IWVSRF)=0.555
                  PARAMS(1)= 0.1212
                  PARAMS(2)= 0.0000
                  PARAMS(3)= 0.0000
                  PARAMS(4)= 0.0000
              ELSEIF(IWVSRF.EQ.3)THEN
                  WVSURF(MLOSP1,IWVSRF)=0.650
                  PARAMS(1)= 0.1648
                  PARAMS(2)= 0.0000
                  PARAMS(3)= 0.0000
                  PARAMS(4)= 0.0000
              ELSEIF(IWVSRF.EQ.4)THEN
                  WVSURF(MLOSP1,IWVSRF)=0.827
                  PARAMS(1)= 0.2757
                  PARAMS(2)= 0.0000
                  PARAMS(3)= 0.0000
                  PARAMS(4)= 0.0000
              ENDIF
          ENDIF
      ELSEIF(CHARIN.EQ.'CARD5')THEN

!         CARD5:
!         READ(IRD,'(I5,A1,F9.0)')IRPT,AMOD3D,FACMC

!         PERFORM REPEAT RUNS FOR ALL ATMOSPHERIC PROFILES:
!           (NH2O+1) H2O PROFILES, 2 CO2 PROFILES AND 2 O3 PROFILES.
          IATM=MOD(IATM+1,4*NH2O+4)
          IF(IATM.EQ.0)THEN
              IRPT=0
          ELSE
              IRPT=1
          ENDIF
          AMOD3D='T'
          FACMC=1.
      ENDIF

      RETURN
      END
