      REAL FUNCTION INTEXP(X,X1,X2,F1,F2)

!     INTEXP EXPONENTIALLY INTERPOLATES TO DETERMINE THE VALUE OF F
!     AT X, GIVEN F1 AT X1 AND F2 AT X2, WITH NO ARGUMENT CHECKING!
      INTEXP=F1*(F2/F1)**((X-X1)/(X2-X1))
      RETURN
      END
