      INTEGER FUNCTION JOU(CHAR01,JBLANK)

!     JOU TRANSLATES A CHARACTER INPUT INTO AN INTEGER LABEL.

!     INPUT ARGUMENTS:
!       CHAR01   CHARACTER TO BE INTERPRETED
!       JBLANK   INDEX TO BE ASSIGNED IF CHAR01 IS BLANK
      CHARACTER CHAR01*1
      INTEGER JBLANK

!     PARAMETERS:
      INCLUDE 'PARAMS.h'

!     COMMONS:
      INCLUDE 'IFIL.h'

!     DECLARE BLOCK DATA ROUTINES EXTERNAL:
      EXTERNAL DEVCBD

!     DATA:
!       CHAR31   ACCEPTABLE VALUES FOR CHAR01
      CHARACTER CHAR31*31
      DATA CHAR31/'12345600 ABCDEFGHIJKabcdefghijk'/

!     CHECK FOR STRING:
      JOU=INDEX(CHAR31,CHAR01)
      IF(JOU.EQ.0)THEN

!         CHAR01 IS NOT RECOGNIZED:
          WRITE(IPR,'(/2A)')                                            &
     &      ' JOU: Cannot interpret JCHAR input:  ',CHAR01
          IF(LJMASS)CALL WRTBUF(FATAL)
          STOP ' JOU: Cannot interpret JCHAR input'
      ELSEIF(JOU.EQ.9 .AND. JBLANK.NE.0 .AND. ABS(JBLANK).LE.6)THEN

!         SET DEFAULT VALUE SINCE CHAR01 IS BLANK:
          JOU=JBLANK
      ELSEIF(JOU.GT.20)THEN

!         TRANSLATE LOWER CASE INPUTS:
          JOU=JOU-11
      ENDIF
      RETURN
      END
