      BLOCK DATA KFRMT

!     COMMONS:

!     /K_FRMT/
!       TFRMT    FORMAT FOR OUTPUT OF K-DEPENDENT TRANSMITTANCES.
!       RFRMT    FORMAT FOR OUTPUT OF K-DEPENDENT RADIANCES.
!       HTFRMT   FORMAT FOR OUTPUT OF K-DEPENDENT TRANSMITTANCES HEADER.
!       HRFRMT   FORMAT FOR OUTPUT OF K-DEPENDENT RADIANCES HEADER.
      CHARACTER TFRMT*33,RFRMT*38,HTFRMT*36,HRFRMT*34
      COMMON/K_FRMT/TFRMT,RFRMT,HTFRMT,HRFRMT
      SAVE /K_FRMT/

!     DATA
      DATA TFRMT/'(15X,F10.5,F12.5,F10.5,2X,  F8.5)'/
      DATA RFRMT/'( 15X,F10.5,F12.5,1P,E13.4,2X,  E11.4)'/
      DATA HTFRMT/'(/F10.2,I5,F10.5,15X,A8,1X,  F8.5,/)'/
      DATA HRFRMT/'(/F10.2,I5,F10.5,19X,A8,  F11.5,/)'/

!     END BLOCK DATA KFRMT
      END

      SUBROUTINE LOOP0(KNTRVL,NLOS,VBAND5,VCEN,BNDWID)

!     LOOP0 PERFORMS THE SPECTRAL INITIALIZATIONS FOR ROUTINE LOOP.
      IMPLICIT NONE

!     ARGUMENTS:
!       KNTRVL   NUMBER OF CORRELATED-K SUB-INTERVALS.
!       NLOS     NUMBER OF LINE-OF-SIGHT PATHS.
!       VBAND5   5 CM-1 RESOLUTION DATA SPECTRAL FREQUENCY [CM-1].
!       VCEN     SPECTRAL-BIN CENTRAL FREQUENCY [CM-1].
!       BNDWID   BAND MODEL SPECTRAL WIDTH [CM-1].
      INTEGER KNTRVL,NLOS
      REAL VBAND5,VCEN,BNDWID

!     PARAMETERS:
      INCLUDE 'PARAMS.h'

!     COMMONS:
      INCLUDE 'BASE.h'
      INCLUDE 'IFIL.h'
      INCLUDE 'YPROP.h'

!     /CORKDT/
!       WTKSUB   SPECTRAL BIN SUB-INTERVAL FRACTIONAL WIDTHS.
!       WTKSAV   SAVED SPECTRAL BIN SUB-INTERVAL FRACTIONAL WIDTHS.
!       DEPLAY   INCREMENTAL OPTICAL DEPTHS.
!       TRNLAY   INCREMENTAL TRANSMITTANCES.
!       TRNCUM   CUMULATIVE TRANSMITTANCES.
!       K2TAIL   POINTER FROM K BIN TO LINE TAIL SUB-BIN
!                (=0 IF MULTIPLE LINE TAIL SUB-BINS CONTRIBUTE).
!       CONTWT   WEIGHTS FOR PARTITIONING LINE TAILS INTO K'S
!                (ONLY USED IF K2TAIL IS 0).
      REAL WTKSUB(MXKSUB),WTKSAV(NTLSUB),DEPLAY(MXKSUB),                &
     &  TRNLAY(MXKSUB),TRNCUM(MXKSUB),CONTWT(NTLSUB,MXKSUB)
      INTEGER K2TAIL(MXKSUB)
      COMMON/CORKDT/K2TAIL,WTKSUB,WTKSAV,DEPLAY,TRNLAY,TRNCUM,CONTWT
      SAVE /CORKDT/

!       SUBINT   SPECTRAL BIN "K" SUB-INTERVAL FRACTIONAL WIDTHS.
!       UPFLX    LAYER BOUNDARY UPWARD THERMAL SPECTRAL
!                FLUX (INCLUDES SCATTERED SOLAR IF DISORT
!                & NO AZIMUTH DEPENDENCE) [W CM-2 / CM-1].
!       DNFLX    LAYER BOUNDARY DOWNWARD THERMAL SPECTRAL
!                FLUX (INCLUDES SCATTERED SOLAR IF DISORT
!                & NO AZIMUTH DEPENDENCE) [W CM-2 / CM-1].
!       UPFLXS   LAYER BOUNDARY UPWARD SCATTERED SOLAR
!                SPECTRAL FLUX (USED WITH DISORT ONLY
!                IF AZIMUTH DEPENDENT) [W CM-2 / CM-1].
!       DNFLXS   LAYER BOUNDARY DOWNWARD SCATTERED SOLAR
!                SPECTRAL FLUX (USED WITH DISORT ONLY
!                IF AZIMUTH DEPENDENT) [W CM-2 / CM-1].
!       NTFLX    LAYER BOUNDARY NET (THERMAL PLUS SCATTERED SOLAR PLUS
!                DIRECT SOLAR) UPWARD SPECTRAL FLUX [W CM-2 / CM-1].
      REAL SUBINT,UPFLX,DNFLX,UPFLXS,DNFLXS,NTFLX
      COMMON/NETFLX/SUBINT(MXKSUB),UPFLX(LAYDIM),DNFLX(LAYDIM),         &
     &  UPFLXS(LAYDIM),DNFLXS(LAYDIM),NTFLX(LAYDIM)

!     /K_FRMT/
!       TFRMT    FORMAT FOR OUTPUT OF K-DEPENDENT TRANSMITTANCES.
!       RFRMT    FORMAT FOR OUTPUT OF K-DEPENDENT RADIANCES.
!       HTFRMT   FORMAT FOR OUTPUT OF K-DEPENDENT TRANSMITTANCES HEADER.
!       HRFRMT   FORMAT FOR OUTPUT OF K-DEPENDENT RADIANCES HEADER.
      CHARACTER TFRMT*33,RFRMT*38,HTFRMT*36,HRFRMT*34
      COMMON/K_FRMT/TFRMT,RFRMT,HTFRMT,HRFRMT
      SAVE /K_FRMT/

!     /SEG5DT/
!       SPCHI    LINE-OF-SIGHT SPECTRAL DATA @ HIGHER 5 CM-1 GRID POINT.
!       SPCMHI   VERTICAL PATH SPECTRAL DATA @ HIGHER 5 CM-1 GRID POINT.
!       SPCLO    LINE-OF-SIGHT SPECTRAL DATA @ LOWER 5 CM-1 GRID POINT.
!       SPCMLO   VERTICAL PATH SPECTRAL DATA @ LOWER 5 CM-1 GRID POINT.
!            1   SEGMENT SCATTERING OD WEIGHTED ASYMMETRY FACTOR
!            2   SEGMENT AEROSOL SCATTERING OPTICAL DEPTH
!            3   TOTAL O2 CONTINUUM TRANSMITTANCE.
!            4   N2 CONTINUUM TRANSMITTANCE.
!            5   TOTAL H2O CONTINUUM TRANSMITTANCE.
!            6   RAYLEIGH MOLECULAR SCATTERED TRANSMITTANCE.
!            7   TRANSMITTANCE FROM AEROSOL EXTINCTION.
!            8   TOTAL OZONE CONTINUUM TRANSMITTANCE.
!            9   ALL CONTINUUM TRANSMITTANCES EXCEPT O2 AND HNO3.
!           10   TRANSMITTANCE FROM AEROSOL ABSORPTION.
!           11   HNO3 TRANSMITTANCE.
!           12   MOLECULAR CONTINUUM OPTICAL DEPTH
!           13   SEGMENT AEROSOL EXTINCTION OPTICAL DEPTH
!           14   COMBINED SPECIES INCREMENTAL CONTINUUM OPTICAL DEPTH
!           15   RAYLEIGH MOLECULAR SCATTERING OPTICAL DEPTH
!           16   CIRRUS CLOUD TRANSMITTANCE (ICLD=20 ONLY)
!           17   UV/VIS NO2 TRANSMISSION
!           18   UV/VIS SO2 TRANSMISSION
!           19   SEGMENT WATER DROPLET SCATTERING OPTICAL DEPTH
!           20   SEGMENT ICE PARTICLE SCATTERING OPTICAL DEPTH
!           21   SEGMENT BOUNDARY LAYER AEROSOL SCATTERING OPTICAL DEPTH
!           22   SEGMENT TROPOSPHERIC AEROSOL SCATTERING OPTICAL DEPTH
!           23   SEGMENT STRATOSPHERIC AEROSOL SCATTERING OPTICAL DEPTH
!           24   SEGMENT MESOSPHERIC+ AEROSOL SCATTERING OPTICAL DEPTH
!           25   SEGMENT NOVAM AEROSOL SCATTERING OPTICAL DEPTH
!           26   SEGMENT NOVAM AEROSOL ASYMMETRY FACTOR
!           27   SEGMENT STD OR SUB-VIS CIRRUS SCATTERING OPTICAL DEPTH
!           28   SEGMENT CLOUD EXTINCTION OPTICAL DEPTH
!           29   SEGMENT CLOUD SCATTERING OD WEIGHTED ASYMMETRY FACTOR
!           30   SEGMENT RAIN EXTINCTION OPTICAL DEPTH
!           31   SEGMENT RAIN SCATTERING OPTICAL DEPTH
!           32   SEGMENT RAIN ASYMMETRY FACTOR
!           33   "14" WITHOUT RAIN, CLOUD AND AEROSOL.
!      NSEG5-2   VIS/NIR CH4 OPTICAL DEPTH
!      NSEG5-1   H2-H2 DIMER OPTICAL DEPTH
!        NSEG5   H2-HE DIMER OPTICAL DEPTH
!       SSAPH    LOS SAP SCATTERING OPTICAL DEPTH @ HIGHER 5 CM-1 POINT.
!       SSAPHM   MS SAP SCATTERING OPTICAL DEPTH @ HIGHER 5 CM-1 POINT.
!       SSAPL    LOS SAP SCATTERING OPTICAL DEPTH @ LOWER 5 CM-1 POINT.
!       SSAPLM   MS SAP SCATTERING OPTICAL DEPTH @ LOWER 5 CM-1 POINT.
!       TXLEG    SPECTRALLY INTERPOLATED LEGENDRE COEFFICIENTS FOR THE
!                SCATTERING PHASE FUNCTION (OPTICAL DEPTH WEIGHTED SUM).
      REAL SPCHI,SPCMHI,SPCLO,SPCMLO,SSAPH,SSAPHM,SSAPL,SSAPLM,TXLEG
      COMMON/SEG5DT/SPCHI(NSEG5,LAYTWO,MLOS,3),SPCMHI(NSEG5,LAYDIM,3),  &
     &  SPCLO(NSEG5,LAYTWO,MLOS,3),SPCMLO(NSEG5,LAYDIM,3),              &
     &  SSAPH(LAYTWO,MLOS,3),SSAPHM(LAYDIM,3),SSAPL(LAYTWO,MLOS,3),     &
     &  SSAPLM(LAYDIM,3),TXLEG(2:MXCMU,1:LAYDIM,0:1)
      SAVE/SEG5DT/

!     /CARD2/
!       IHAZE    BOUNDARY LAYER AEROSOL MODEL NUMBER.
!       ISEASN   SEASON NUMBER (1=SPRING-SUMMER, 2=FALL-WINTER).
!       IVULCN   VOLCANIC AEROSOL MODEL NUMBER.
!       ICSTL    COASTAL AIRMASS MODEL NUMBER.
!       ICLD     CLOUD MODEL NUMBER.
!       IVSA     VERTICAL STRUCTURE ALGORITHM (0=OFF, 1=ON).
!       VIS      SURFACE VISIBILITY (GROUND METEOROLOGICAL RANGE) [KM].
!       WSS      CURRENT WIND SPEED (M/S).
!       WHH      24-HOUR WIND SPEED (M/S).
!       RAINRT   RAIN RATE (MM/HR)
!       LSAP     LOGICAL FLAG FOR SPECTRAL AEROSOL PROFILES INPUT.
      INTEGER IHAZE,ISEASN,IVULCN,ICSTL,ICLD,IVSA
      REAL VIS,WSS,WHH,RAINRT
      LOGICAL LSAP
      COMMON/CARD2/IHAZE,ISEASN,IVULCN,ICSTL,ICLD,IVSA,                 &
     &  VIS,WSS,WHH,RAINRT,LSAP

!     /SAP/
!       NWVSAP   NUMBER OF AEROSOL SPECTRAL GRID POINTS.
!       NLGSAP   HIGHEST AEROSOL PHASE FUNCTION LEGENDRE MOMENT.
!       NANSAP   NUMBER OF AEROSOL PHASE FUNCTION ANGULAR POINTS.
!       LEVSAP   NUMBER OF AEROSOL ATMOSPHERIC LEVELS.
!       ANGSAP   AEROSOL PHASE FUNCTION ANGULAR GRID [DEGREES].
!       COSSAP   COSINE OF THE AEROSOL PHASE FUNCTION ANGLES.
!       WAVSAP   AEROSOL SPECTRAL GRID [MICRONS].
!       LEGSAP   AEROSOL LEGENDRE COEFFICIENTS.
!       PFSAP    AEROSOL PHASE FUNCTION [SR-1].
!       LOSSAP   LOGICAL FLAG, TRUE FOR LINE-OF-SIGHT PATH.
      INTEGER NWVSAP,NLGSAP,NANSAP,LEVSAP
      DOUBLE PRECISION ANGSAP,COSSAP,PFSAP
      REAL WAVSAP,LEGSAP
      LOGICAL LOSSAP
      COMMON/SAP/NWVSAP,NLGSAP,NANSAP,LEVSAP,ANGSAP(MANSAP),            &
     &  COSSAP(MANSAP),WAVSAP(MWVSAP),LEGSAP(MLGSAP,MWVSAP,LAYDIM),     &
     &  PFSAP(MANSAP,MWVSAP,LAYDIM),LOSSAP

!     /SAPV/
!       ILOSAP   SAP DATA LOWER WAVELENGTH INDEX AT CURRENT FREQUENCY.
!       IHISAP   SAP DATA HIGHER WAVELENGTH INDEX AT CURRENT FREQUENCY.
!       FRCSAP   SAP DATA INTERPOLATION FRACTION AT CURRENT FREQUENCY.
      INTEGER ILOSAP,IHISAP
      REAL FRCSAP
      COMMON/SAPV/ILOSAP,IHISAP,FRCSAP

!     /DISRT/
!       UMU      MONOTONICALLY INCREASING LIST OF DISTINCT USER-PATH
!                COSINE POLAR ANGLES.
!       PHI      MONOTONICALLY INCREASING LIST OF DISTINCT RELATIVE
!                SOLAR AZIMUTH ANGLES [0 TO 180 DEG].
!       NSTR     NUMBER OF DISCRETE ORDINATE STREAMS.
!       NAZ      NUMBER OF DISORT AZIMUTH COMPONENTS.
!       N2GAUS   ORDER OF DOUBLE-GAUSS QUADRATURES.
!       NUMU     NUMBER OF DISTINCT USER LINE-OF-SIGHT POLAR ANGLES.
!       MAPUMU   MAPPING FROM LINE-OF-SIGHT INDEX TO UMU ARRAY ENTRY.
!       NPHI     NUMBER OF DISTINCT RELATIVE SOLAR AZIMUTH ANGLES.
!       MAPPHI   MAPPING FROM LINE-OF-SIGHT INDEX TO PHI ARRAY ENTRY.
!       DIS      LOGICAL FLAG, TRUE FOR DISORT MULTIPLE SCATTERING.
!       DISAZM   LOGICAL FLAG, TRUE FOR DISORT WITH AZIMUTH DEPENDENCE.
!       DISALB   LOGICAL FLAG, TRUE FOR DISORT SPHERICAL ALBEDO OPTION.
!       LDISCL   LOGICAL FLAG, TRUE FOR ISAACS SCALED TO DISORT.
      REAL UMU,PHI
      INTEGER NSTR,NAZ,N2GAUS,NUMU,MAPUMU,NPHI,MAPPHI
      LOGICAL DIS,DISAZM,DISALB,LDISCL
      COMMON/DISRT/UMU(MXUMU),PHI(MAXPHI),NSTR,NAZ,N2GAUS,NUMU,         &
     &  MAPUMU(MLOS),NPHI,MAPPHI(MLOS),DIS,DISAZM,DISALB,LDISCL
      SAVE /DISRT/

!     /CNTRL/
!       NSEG     NUMBER OF PATH SEGMENTS ALONG LINE-OF-SIGHT.
!       ML       NUMBER OF ATMOSPHERIC PROFILE LEVELS.
!       MLFLX    NUMBER OF LEVELS FOR WHICH FLUX VALUES ARE WRITTEN.
!       IMULT    MULTIPLE SCATTERING FLAG
!                  (0=NONE, 1=AT SENSOR, -1=AT FINAL OR TANGENT POINT).
!       THERML   FLAG TO CALCULATE THERMAL SCATTER.
      INTEGER NSEG,ML,MLFLX,IMULT
      LOGICAL THERML
      COMMON/CNTRL/NSEG(0:MLOSP1),ML,MLFLX,IMULT,THERML

!     /CARD1/
!       MODEL    MODEL ATMOSPHERE INDEX.
!       ITYPE    SLANT PATH TYPE.
!       IEMSCT   RADIATIVE TRANSFER MODE.
!                  0 FOR TRANSMITTANCE
!                  1 FOR THERMAL EMISSION ONLY
!                  2 FOR THERMAL EMISSION PLUS SOLAR SCATTER
!                  3 FOR TRANSMITTED SOLAR IRRADIANCE
!                  4 FOR SOLAR SCATTER ONLY
!       M1       MODEL ATMOSPHERE FOR PRESSURE & TEMPERATURE PROFILES.
!       M2       MODEL ATMOSPHERE FOR H2O PROFILE.
!       M3       MODEL ATMOSPHERE FOR O3 PROFILE.
!       I_RD2C   READ CARD 2C, 2C1, ... IF EQUAL 1; SKIP IF EQUAL TO 0.
!       NOPRNT   PRINT FLAG.
!       MODTRN   MODTRAN BAND MODEL FLAG.
      INTEGER MODEL,ITYPE,IEMSCT,M1,M2,M3,I_RD2C,NOPRNT
      LOGICAL MODTRN
      COMMON/CARD1/MODEL,ITYPE,IEMSCT,M1,M2,M3,I_RD2C,NOPRNT,MODTRN

!     /LOOP_0/
!       O3MAX    TOLERANCE FOR 3-PARAMETER CURTIS-GODSON MONOTONICITY.
!       WDKDIS   BAND MODEL WIDTH [CM-1].
!       V0KDIS   CALCULATION INITIAL FREQUENCY.
!       NMWAVE   WAVELENGTH BIN OF PREVIOUS DATA [NM].
!       NTHEAD   HEADER RECORD FOR K-DEPENDENT TRANSMITTANCE FILE.
!       NRHEAD   HEADER RECORD FOR K-DEPENDENT RADIANCE FILE.
!       N4BYTE   NUMBER OF 4 BYTE VARIABLES PER RECORD.
!       NTREC    NUMBER OF RECORDS PER SPECTRAL POINT IN TRANSM FILE.
!       NRREC    NUMBER OF RECORDS PER SPECTRAL POINT IN RADIANCE FILE.
!       NRANGE   NUMBER OF OUTPUT PATH RANGES.
!       KPRINT   LOGICAL FLAG, DICTATING K-DEPENDENT DATA OUTPUT.
      REAL O3MAX,WDKDIS,V0KDIS
      INTEGER NMWAVE,NTHEAD,NRHEAD,N4BYTE,NTREC,NRREC,NRANGE
      LOGICAL KPRINT
      COMMON/LOOP_0/O3MAX,WDKDIS,V0KDIS,                                &
     &  NMWAVE,NTHEAD,NRHEAD,N4BYTE,NTREC,NRREC,NRANGE,KPRINT
      SAVE /LOOP_0/

!     /CJM5/
!       AMOD3D   FLAG INDICATING OUTPUT DATABASE FILE TYPE:
      CHARACTER AMOD3D*1
      COMMON/CJM5/AMOD3D

!     /AER/ THERE ARE "MAER=17" PARTICULATE COMPONENTS:
!           1       AEROSOL 1 (NOMINALLY, BOUNDARY LAYER AEROSOL).
!           2       AEROSOL 2 (NOMINALLY, TROPOSPHERIC AEROSOL).
!           3       AEROSOL 3 (NOMINALLY, STRATOSPHERIC AEROSOL).
!           4       AEROSOL 4 (NOMINALLY, VOLCANIC AEROSOL).
!           5       CIRRUS CLOUD.
!           6       CLOUD 1 (NOMINALLY, WATER CLOUD).
!           7       CLOUD 2 (NOMINALLY, ICE CLOUD).
!           8-17    NOVAM (NAVY OCEANIC VERTICAL AEROSOL MODEL) LAYERS.
!       NAER     NUMBER OF ACTIVE AEROSOLS.
!       EXTV     SPECTRAL EXTINCTION (NORMALIZED TO 1 AT 550 NM).
!       ABSV     SPECTRAL ABSORPTION (1-ABSV/EXTV=SCATTERING ALBEDO).
!       ASYV     SPECTRAL LEGENDRE MOMENT (DIVIDED BY 2N+1).
!       FRAC5    5 CM-1 GRID SPECTRAL INTERPOLATION FRACTION.
!       ASYVLO   ASYMMETRY FACTOR FROM PREVIOUS SPECTRAL FREQUENCY.
      INTEGER NAER
      REAL EXTV,ABSV,ASYV,FRAC5,ASYVLO
      COMMON/AER/NAER,EXTV(MAER),ABSV(MAER),ASYV(MXCMU,MAER),           &
     &  FRAC5,ASYVLO(MAER)

!     /PATH/
!       PTHCOS   COSINE OF PATH ZENITH AT PATH BOUNDARIES.
!       PTHZEN   PATH ZENITH AT PATH BOUNDARIES [DEG].
!       PTHECA   SENSOR TO PATH EARTH CENTER ANGLE [DEG].
!       PTHALT   ALTITUDES AT PATH BOUNDARIES [KM].
!       PTH_MS   ALTITUDES AT PATH BOUNDARIES FOR THE MS PATH.
!       PTHSEG   PATH SEGMENT LENGTH [KM].
!       PTHRNG   SENSOR TO PATH BOUNDARY RANGE [KM].
!       JMAX     NUMBER OF DISTINCT LOS PATH SEGMENT ENDPOINT ALTITUDES.
!       IKHMIN   PATH BOUNDARY INDEX OF PATH MINIMUM ALTITUDE.
!       IKHMAX   PATH BOUNDARY INDEX OF PATH MAXIMUM ALTITUDE.
!       IKOUT    NUMBER OF PATH BOUNDARIES K DATA IS OUTPUT.
!       NTKDIS   RECORD NUMBER FOR K-DISTRIBUTION TRANSMITTANCE FILE.
!       NRKDIS   RECORD NUMBER FOR K-DISTRIBUTION RADIANCE FILE.
!       MAPPTH   MAPPING FROM PATH SEGMENT MIDPOINT TO VERTICAL LAYER.
!       IPTHHT   ALTITUDES (HEIGHTS) AT PATH BOUNDARIES [M].
!       LOWALT   VERTICAL LAYER BOUNDARY INDEX AT OR JUST BELOW PTHALT.
!       FACALT   ALTITUDE INTERPOLATION FRACTION FOR PTHALT
!       PATH_T   TEMPERATURE AT PATH BOUNDARIES [K].
!       PATH_P   PRESSURE AT PATH BOUNDARIES [ATM].
!       PTHRH    RELATIVE HUMIDITY AT PATH BOUNDARIES [K].
!       LSSGEO   LOGICAL FLAG, .TRUE. FOR SOLAR PATHS.
!       LTANMX   LOGICAL FLAG, .TRUE. IF PATH HAS A TANGENT MAXIMUM.
      DOUBLE PRECISION PTHCOS,PTHZEN,PTHECA,PTHALT,PTH_MS,PTHSEG,PTHRNG
      INTEGER JMAX,IKHMIN,IKHMAX,IKOUT,NTKDIS,NRKDIS,MAPPTH,            &
     &  IPTHHT,LOWALT
      REAL FACALT,PATH_T,PATH_P,PTHRH
      LOGICAL LSSGEO,LTANMX
      COMMON/PATH/PTHCOS(0:LAYTWO),PTHZEN(0:LAYTWO),PTHECA(0:LAYTWO),   &
     &  PTHALT(0:LAYTWO,1:MLOS),PTH_MS(0:LAYDIM),PTHSEG(LAYTWO),        &
     &  PTHRNG(0:LAYTWO,1:MLOS),JMAX,IKHMIN(MLOS),IKHMAX(MLOS),         &
     &  IKOUT(MLOS),MAPPTH(LAYTWO,1:MLOS),IPTHHT(0:LAYTWO),NTKDIS,      &
     &  NRKDIS,LOWALT(0:LAYTWO,1:MLOS),FACALT(0:LAYTWO,1:MLOS),         &
     &  PATH_T(0:LAYTWO,1:MLOS),PATH_P(0:LAYTWO,1:MLOS),                &
     &  PTHRH(0:LAYTWO,1:MLOS),LSSGEO,LTANMX

!     LOCAL VARIABLES:
!       INTRVL   LOOP INDEX FOR CORRELATED-K SUB-INTERVALS.
!       ISEG     PATH SEGMENT LOOP INDEX.
!       ILOS     LINE-OF-SIGHT LOOP INDEX.
!       KSPEC5   INDEX FOR SPECIES CHARACTERIZED BY 5CM-1 SPECTRAL DATA.
!       ISTR     LOOP INDEX FOR MULTIPLE SCATTERING STREAMS.
!       IEXT     LOOP INDEX FOR EXTINCTION SOURCES.
!       IAER     LOOP INDEX FOR PARTICULATE COMPONENTS.
      INTEGER INTRVL,ISEG,ILOS,KSPEC5,ISTR,IEXT,IAER

!     DEFINE THE CORRELATED-K SPECTRAL BIN WEIGHTS:
      IF(KNTRVL.GT.1)THEN
          DO INTRVL=1,KNTRVL
              SUBINT(INTRVL)=WTKSUB(INTRVL)
          ENDDO
          WRITE(TFRMT(27:28),'(I2)')KNTRVL
          WRITE(RFRMT(31:32),'(I2)')KNTRVL
      ELSE
          SUBINT(1)=1.
      ENDIF

!     INITIALIZE OPTICAL DEPTH ARRAYS
      DO ILOS=1,NLOS
          DO ISEG=1,NSEG(ILOS)
              DO KSPEC5=1,NSEG5
                  SPCLO(KSPEC5,ISEG,ILOS,1)=0.
                  SPCHI(KSPEC5,ISEG,ILOS,1)=0.
                  SPCLO(KSPEC5,ISEG,ILOS,2)=0.
                  SPCHI(KSPEC5,ISEG,ILOS,2)=0.
                  SPCLO(KSPEC5,ISEG,ILOS,3)=0.
                  SPCHI(KSPEC5,ISEG,ILOS,3)=0.
              ENDDO
          ENDDO
      ENDDO
      IF(LSAP)THEN
          ILOSAP=NWVSAP-1
          DO ILOS=1,NLOS
              DO ISEG=1,NSEG(ILOS)
                  SSAPL(ISEG,ILOS,1)=0.
                  SSAPH(ISEG,ILOS,1)=0.
                  SSAPL(ISEG,ILOS,2)=0.
                  SSAPH(ISEG,ILOS,2)=0.
                  SSAPL(ISEG,ILOS,3)=0.
                  SSAPH(ISEG,ILOS,3)=0.
              ENDDO
          ENDDO
      ENDIF

!     INITIALIZE X AND Y MOLECULAR SPECIES TRANSMITTANCES:
      DO IEXT=MEXT+1,MEXTX+NMOLY
          TX(IEXT)=1.
      ENDDO

!     INITIALIZATION FOR MULTIPLE SCATTERING CALCULATIONS:
      IF(IMULT.NE.0)THEN
          DO ISEG=1,NSEG(MLOSP1)
              DO KSPEC5=1,NSEG5
                  SPCMLO(KSPEC5,ISEG,1)=0.
                  SPCMHI(KSPEC5,ISEG,1)=0.
                  SPCMLO(KSPEC5,ISEG,2)=0.
                  SPCMHI(KSPEC5,ISEG,2)=0.
                  SPCMLO(KSPEC5,ISEG,3)=0.
                  SPCMHI(KSPEC5,ISEG,3)=0.
              ENDDO
          ENDDO
          IF(LSAP)THEN
              DO ISEG=1,NSEG(MLOSP1)
                  SSAPLM(ISEG,1)=0.
                  SSAPHM(ISEG,1)=0.
                  SSAPLM(ISEG,2)=0.
                  SSAPHM(ISEG,2)=0.
                  SSAPLM(ISEG,3)=0.
                  SSAPHM(ISEG,3)=0.
              ENDDO
          ENDIF
          IF(DIS)THEN
              DO ISTR=2,NSTR
                  DO ISEG=1,LAYDIM
                      TXLEG(ISTR,ISEG,0)=0.
                      TXLEG(ISTR,ISEG,1)=0.
                  ENDDO
              ENDDO
          ENDIF
          CALL MAPMS(NLOS)
      ENDIF

!     INITIALIZATION FOR LOWTRAN CALCULATIONS:
      IF(.NOT.MODTRN)CALL FRQ5DT(.TRUE.,VBAND5)

!     INITIALIZATION FOR MOD3D DATABASE GENERATION:
      NMWAVE=0
      IF(AMOD3D.EQ.'T')CALL M3DIN(NSEG(1))

!     INITIALIZE ASYMMETRY FACTORS:
      DO IAER=1,MAER
          ASYV(1,IAER)=0.
      ENDDO

!     GET HEADER FOR K-DISTRIBUTION DEPENDENT DATA FILES:
      KPRINT=NOPRNT.LE.3 .AND. IKOUT(1).GE.0
      IF(KPRINT .AND. BINOUT)THEN
          WDKDIS=BNDWID
          V0KDIS=VCEN+BNDWID
          NTKDIS=NTKDIS+1
          NTHEAD=NTKDIS
          READ(JTKDIS,REC=NTKDIS)N4BYTE,NTREC,NRANGE
          NRKDIS=NRKDIS+1
          NRHEAD=NRKDIS
          READ(JRKDIS,REC=NRKDIS)N4BYTE,NRREC,NRANGE
      ENDIF
      O3MAX=.001
      RETURN
      END
