      SUBROUTINE M3DDB(KNTRVL,IKMAX,LABEL)

!     M3DDB GENERATES THE MOD3D MOLECULAR DATA FILE BY CALLING M3DREW.
      IMPLICIT NONE

!     PARAMETERS:
      INCLUDE 'PARAMS.h'

!     INPUT ARGEMENTS:
!       KNTRVL   NUMBER OF ABSORPTION COEFFICIENT (K) SUB-INTERVALS.
!       IKMAX    NUMBER OF PATH SEGMENTS.
      INTEGER KNTRVL,IKMAX
      CHARACTER LABEL*6

!     COMMONS:
      INCLUDE 'IFIL.h'

!     /CARD4/
!       IV1      LOWEST SPECTRAL FREQUENCY OUTPUT [CM-1].
!       IV2      HIGHEST SPECTRAL FREQUENCY OUTPUT [CM-1].
!       IDV      PRINTOUT SPECTRAL FREQUENCY STEP SIZE [CM-1].
!       IFWHM    TRIANGULAR SLIT FULL-WIDTH-HALF-MAXIMUM [CM-1].
!       VBAND    CURRENT COMPUTATION BAND FREQUENCY [CM-1].
!                (EQUALS BAND CENTER FOR 1, 5 & 15 CM-1 BAND MODELS;
!                EQUALS THE MINIMUM BAND VALUE FOR 0.1 CM-1 BAND MODEL)
!       IBINPT   BIN NUMBER OF CURRENT SPECTRAL POINT.
!                (CENTER FREQUENCY = IBINPT * BNDWID + OSHIFT).
!       IBINLO   BIN NUMBER OF (PADDED) SPECTRAL RANGE LOWER BOUND.
!       IBINHI   BIN NUMBER OF (PADDED) SPECTRAL RANGE UPPER BOUND.
!       IBINMN   BIN NUMBER OF MINIMUM COMPUTATION SPECTRAL POINT.
!       IBINMX   BIN NUMBER OF MAXIMUM COMPUTATION SPECTRAL POINT.
!       IBINDL   BIN NUMBER INCREMENT FOR SPECTRAL PRINTOUT.
!       IBINRS   BIN NUMBER INCREMENT EQUAL TO SPECTRAL RESOLUTION.
!       IBINOS   BIN NUMBER OFFSET BETWEEN CURRENT & OUTPUT SPC POINTS.
!       IBINWR   BIN NUMBER OF NEXT SPECTRAL DATA WRITE.
!       MBINPT   BIN NUMBER MAXIMUM FOR CURRENT BAND MODEL RESOLUTION.
!       IDBIN5   SPECTRAL BIN NUMBER STEP SIZE FOR 5 CM-1 GRID.
!       ISTEP5   INCREMENT FOR RETRIEVING 5 CM-1 RESOLUTION DATA [CM-1].
!       NSPCDT   NUMBER OF OUTPUT SPECTRAL DATA POINTS.
      DOUBLE PRECISION IDV
      REAL IV1,IV2,IFWHM,VBAND
      INTEGER IBINPT,IBINLO,IBINHI,IBINMN,IBINMX,IBINDL,                &
     &  IBINRS,IBINOS,IBINWR,MBINPT,IDBIN5,ISTEP5,NSPCDT
      COMMON/CARD4/IDV,IV1,IV2,IFWHM,VBAND,IBINPT,IBINLO,IBINHI,IBINMN, &
     &  IBINMX,IBINDL,IBINRS,IBINOS,IBINWR,MBINPT,IDBIN5,ISTEP5,NSPCDT

!     /M3DSPC/
!       LASCII   ASCII FILE OUTPUT FLAG FOR MOD3D FILES.
!       NATM     COUNTER FOR NUMBER OF DIFFERENT MOLECULAR ATMOSPHERES.
      LOGICAL LASCII
      INTEGER NATM
      COMMON/M3DSPC/LASCII,NATM

!     /M3DNAM/
!       M3DGEN   NAME OF GENERAL INFORMATION FILE FOR MOD3D.
!       M3DCNT   NAME OF CONTINUA DATA FILE FOR MOD3D.
!       M3DDAT   NAME OF MOLECULAR EXTINCTION FILE SORTED BY ATMOSPHERE.
!       M3DMOL   NAME OF MOLECULAR EXTINCTION DATA FILE FOR MOD3D.
      CHARACTER M3DGEN*(NAMLEN),M3DCNT*(NAMLEN),                        &
     &  M3DDAT*(NAMLEN),M3DMOL*(NAMLEN)
      COMMON/M3DNAM/M3DGEN,M3DCNT,M3DDAT,M3DMOL
      EXTERNAL DEVCBD

!     LOCAL VARIABLES:
!       NBIN     NUMBER OF SPECTRAL DATA POINTS.
      INTEGER NBIN

!     RETURN IF ASCII FORMAT IS BEING USED:
      IF(LASCII)RETURN

!     NUMBER OF SPECTRAL DATA POINTS:
      NBIN=IBINMX-IBINMN+1

!     RE-WRITE MOLECULAR DATA:
      CALL M3DREW(NBIN,KNTRVL,IKMAX,NATM,I3DGEN,I3DDAT,I3DMOL,M3DMOL,    &
     &      LABEL )

!     RETURN TO DRIVER:
      RETURN
      END
