      SUBROUTINE NEWH2(REARTH,ZMAX,                                     &
     &  H1ALT,H2ALT,OBSZEN,HRANGE,BETA,LENN,HTAN,BCKZEN)

!     NEWH2 DETERMINES
!       HTAN     TANGENT HEIGHT [KM],
!       H2ALT    FINAL ALTITUDE [KM],
!       BETA     EARTH CENTER ANGLE [DEG], AND
!       LENN     PATH SWITCH (=1 IF PATH PASSES THROUGH HTAN)
!     GIVEN INPUTS
!       REARTH   RADIUS OF THE EARTH [KM].
!       ZMAX     MAXIMUM ATMOSPHERIC PROFILE ALTITUDE [KM].
!       H1ALT    INITIAL (OBSERVER) ALTITUDE [KM],
!       OBSZEN   PATH ZENITH ANGLE AT H1ALT [DEG], AND
!       HRANGE   PATH SLANT HRANGE.
      IMPLICIT NONE

!     INPUT ARGUMENTS:
      DOUBLE PRECISION REARTH,ZMAX,H1ALT,OBSZEN,HRANGE

!     OUTPUT ARGUMENTS:
      DOUBLE PRECISION H2ALT,BETA,HTAN,BCKZEN
      INTEGER LENN

!     COMMONS:

!     /DCNSTN/
!       DRIGHT   SMALLEST DOUBLE PRECISION REAL ADDED TO 1 EXCEEDS 1.
!       DPDEG    NUMBER OF DEGREES IN ONE RADIAN IN DOUBLE PRECISION
      DOUBLE PRECISION DRIGHT,DPDEG
      COMMON/DCNSTN/DRIGHT,DPDEG

!     LOCAL VARIABLES:
      DOUBLE PRECISION RX,CPATH,RXRAT

!     FUNCTIONS:
      DOUBLE PRECISION TANHT

!     COMPUTE CPATH, THE PATH CONSTANT,
      CALL IRFXN(H1ALT,RX,RXRAT)
      CPATH=RX*SIN(OBSZEN/DPDEG)*(H1ALT+REARTH)

!     FIND HTAN, H2ALT, BETA AND LENN.
      HTAN=TANHT(CPATH,REARTH)
      CALL FNDPTH(CPATH,REARTH,ZMAX,                                    &
     &  H1ALT,HTAN,H2ALT,HRANGE,BETA,LENN,OBSZEN,BCKZEN)
      IF(OBSZEN.LE.90.)HTAN=MIN(H1ALT,H2ALT)

!     ROUTINE OPERATIONS COMPLETED.
      RETURN
      END
