      REAL FUNCTION O3HHT2(V)

!     COMMONS:
      INTEGER N_HH2
      REAL V1_HH2,DV_HH2,O3HH2X
      COMMON/O3HH2/V1_HH2,DV_HH2,N_HH2,O3HH2X(2687)

!     DECLARE BLOCK DATA ROUTINES EXTERNAL:
      SAVE /O3HH2/
      EXTERNAL BO3HH2

!     FUNCTIONS:
      REAL O3INT

!     INTERPOLATE TO DATA:
      O3HHT2=O3INT(V,V1_HH2,DV_HH2,N_HH2,O3HH2X)
      RETURN
      END
