      REAL FUNCTION O3HHT1(V)

!     COMMONS:
      INTEGER N_HH1
      REAL V1_HH1,DV_HH1,O3HH1X
      COMMON/O3HH1/V1_HH1,DV_HH1,N_HH1,O3HH1X(2687)

!     DECLARE BLOCK DATA ROUTINES EXTERNAL:
      SAVE /O3HH1/
      EXTERNAL BO3HH1

!     FUNCTIONS:
      REAL O3INT

!     INTERPOLATE TO DATA:
      O3HHT1=O3INT(V,V1_HH1,DV_HH1,N_HH1,O3HH1X)
      RETURN
      END
