      REAL FUNCTION O3HHT0(V)

!     COMMONS:
      INTEGER N_HH0
      REAL V1_HH0,DV_HH0,O3HH0X
      COMMON/O3HH0/V1_HH0,DV_HH0,N_HH0,O3HH0X(2687)

!     DECLARE BLOCK DATA ROUTINES EXTERNAL:
      SAVE /O3HH0/
      EXTERNAL BO3HH0

!     FUNCTIONS:
      REAL O3INT
      O3HHT0=O3INT(V,V1_HH0,DV_HH0,N_HH0,O3HH0X)
      RETURN
      END
