      REAL FUNCTION O3INT(V,V1C,DVC,NC,CONTI)

!     INTERPOLATION FOR O3 CONTINUUM WITH LOWTRAN
      REAL CONTI(2687)
      I=INT((V-V1C)/DVC+1.00001)
      IF(I.GE.1 .AND. I.LE.NC)THEN
          O3INT=CONTI(I)
      ELSE
          O3INT=0.
      ENDIF
      RETURN
      END
