      REAL FUNCTION PF(NN,IWAVE,IANGLE)

!     CALL THE APPROPRIATE PHASE FUNCTION
      INTEGER MNUM
      REAL PHSFNC
      INTEGER NN,IWAVE,IANGLE,M
      COMMON/MNMPHS/MNUM(27,26),PHSFNC(34,70)

!     DECLARE BLOCK DATA ROUTINES EXTERNAL:
      SAVE /MNMPHS/
      EXTERNAL PHSDTA
      M=MNUM(IWAVE,NN)
      PF=PHSFNC(IANGLE,M)
      RETURN
      END
