      SUBROUTINE SAXPY(N,SA,SX,SY)

!     Y = A*X + Y  (X, Y = VECTORS, A = SCALAR)
      IMPLICIT NONE

!     INPUT ARGUMENTS:
!       N        NUMBER OF ELEMENTS IN INPUT VECTORS 'X' AND 'Y'.
!       SA       SINGLE PRECISION SCALAR MULTIPLIER 'A'.
!       SX       SING-PREC ARRAY CONTAINING VECTOR 'X'.
!       SY       SING-PREC ARRAY CONTAINING VECTOR 'Y'.

!     OUTPUT ARGUMENTS:
!       SY       FOR I = 1 TO N, OVERWRITE SY(I) WITH SA*SX(I) + SY(I)
      INTEGER N
      REAL SA,SX(N),SY(N)

!     VECTOR OPERATION:
      IF(N.GT.0 .AND. SA.NE.0.)SY=SA*SX+SY
      RETURN
      END
