
!     /SEGDAT/
!       WTOTAL   TOTAL PATH COLUMN AMOUNT [ATM CM].
!       PATM     LINE-OF-SIGHT SEGMENT DENSITY-WEIGHTED PRESSURE [ATM].
!       PATMMS   VERTICAL MS PATH SEGMENT DENSITY-WEIGHTED PRES [ATM].
!       TSEG     LINE-OF-SIGHT SEGMENT DENSITY-WEIGHTED TEMPERATURE [K].
!       TSEGMS   VERTICAL MS PATH SEGMENT DENSITY-WEIGHTED TEMP [K].
!       DRNG     LINE-OF-SIGHT PATH SEGMENT SLANT RANGE [KM].
!       WPTH     LINE-OF-SIGHT INCREMENTAL MOLECULAR COLUMN AMOUNTS
!                FOR BAND MODEL SPECIES [ATM CM].
!       WPTHMS   VERTICAL MULTIPLE SCATTERING PATH INCREMENTAL MOLECULAR
!                COLUMN AMOUNTS FOR BAND MODEL SPECIES [ATM CM].
      REAL WTOTAL,PATM,PATMMS,TSEG,TSEGMS,DRNG,WPTH,WPTHMS
      COMMON/PATHDT/WTOTAL(0:MEXTXY),PATM(1:LAYTWO,0:MLOS),             &
     &  PATMMS(LAYDIM),TSEG(1:LAYTWO,0:MLOS),TSEGMS(LAYDIM),            &
     &  DRNG(1:LAYTWO,0:MLOS),WPTH(0:MEXTXY,1:LAYTWO,0:MLOS),           &
     &  WPTHMS(0:MEXTXY,1:LAYDIM)
