      SUBROUTINE SINT(V1,V1C,DV,NPT,CONTI,CONTO)

!     INTERPOLATION FOR CONTINUUM WITH LOWTRAN.
      REAL CONTI(2003)
      I=INT((V1C-V1)/DV+1.00001)
      IF(I.GE.NPT)THEN
          CONTO=0.
      ELSEIF(INT(AMOD(V1C,10.)).EQ.0)THEN
          CONTO=CONTI(I)
      ELSE
          CONTO=(CONTI(I)+CONTI(I+1))/2
      ENDIF
      RETURN
      END
