      SUBROUTINE SVSOLA(IPARM,IPH,IDAY,ISOURC,PARM1,PARM2,              &
     &  SRCLAT,SRCLON,GMTIME,G,ANGLEM,IPRMSV,IPHSV,IDAYSV,              &
     &  ISRCSV,PRM1SV,PRM2SV,SLATSV,SLONSV,GMTSV,GSV,ANGMSV)

!     SAVE THE CURRENT SOLAR PARAMETERS.
      INTEGER IPH,IPARM,IDAY,ISOURC,IPRMSV,IPHSV,IDAYSV,ISRCSV
      REAL G,GSV
      DOUBLE PRECISION PARM1,PARM2,SRCLAT,SRCLON,GMTIME,ANGLEM,         &
     &  PRM1SV,PRM2SV,SLATSV,SLONSV,GMTSV,ANGMSV
      IPRMSV=IPARM
      IPHSV=IPH
      IDAYSV=IDAY
      ISRCSV=ISOURC
      PRM1SV=PARM1
      PRM2SV=PARM2
      SLATSV=SRCLAT
      SLONSV=SRCLON
      GMTSV=GMTIME
      GSV=G
      ANGMSV=ANGLEM
      RETURN
      END
