      REAL FUNCTION TNRAIN(RR,V,TMODEL,RADFLD)

!     CALCULATES TRANSMISSION DUE TO RAIN AS A FUNCTION OF
!     RR=RAIN RATE IN MM/HR
!     OR WITHIN 350CM-1 USES THE MICROWAVE TABLE ROUTINE TO
!     OBTAIN THE EXTINCTION DUE TO RAIN
!     RANGE=SLANT RANGE KM
      IMPLICIT NONE

!     PARAMETERS:
!       ASSUMES A MARSHALL-PALMER RAIN DROP SIZE DISTRIBUTION
!       N(D)=NZERO*EXP(-A*D)
!       NZERO=8.E3 (MM-1)  (M-3)
!       A=41.*RR**(-0.21)
!       D=DROP DIAMETER (CM)
!       COEF = 8000 PI / 41**3
      REAL COEF
      PARAMETER(COEF=.36466)

!     INPUT ARGUMENTS:
      REAL RR,V,TMODEL,RADFLD

!     FUNCTIONS:
      REAL GMRAIN

      IF(RR.LE.0.)THEN
          TNRAIN=1.
      ELSEIF(V.GE.350.)THEN
          TNRAIN=COEF*RR**.63
      ELSE
          TNRAIN=GMRAIN(V,TMODEL,RR)*RADFLD
      ENDIF
      RETURN
      END
