      SUBROUTINE UPCASE(STRING)

!     CONVERTS STRING TO UPPER CASE:
      IMPLICIT NONE

!     ARGUMENTS:
!       STRING   INPUT CHARACTER STRING OF VARIABLE LENGTH.
      CHARACTER STRING*(*)

!     LOCAL VARIABLES:
!       I        LOOP INDEX FOR STRING CHARACTERS.
!       LOC      LOCATION OF LETTER IN ALPHABET.
      INTEGER I,LOCATN

!     DATA:
!       UPPER    UPPER CASE ALPHABET.
!       LOWER    LOWER CASE ALPHABET.
      CHARACTER UPPER*26,LOWER*26
      SAVE UPPER,LOWER
      DATA UPPER /'ABCDEFGHIJKLMNOPQRSTUVWXYZ'/
      DATA LOWER /'abcdefghijklmnopqrstuvwxyz'/

      DO I=1,LEN(STRING)
         LOCATN=INDEX(LOWER,STRING(I:I))
         IF(LOCATN.GT.0)STRING(I:I)=UPPER(LOCATN:LOCATN)
      ENDDO

      RETURN
      END

      SUBROUTINE MVRGT(CHRSTR)

!     ELIMINATE TRAILING BLANKS BY MOVING STRING TO THE RIGHT
!     AND INSERTING LEADING BLANKS.
      IMPLICIT NONE

!     ARGUMENT:
      CHARACTER CHRSTR*(*)

!     LOCAL VARIABLES:
      INTEGER I,ISTART,MAXLEN

      MAXLEN=LEN(CHRSTR)

      DO I=MAXLEN,1,-1
         IF(CHRSTR(I:I).NE.' ')GOTO 10
      ENDDO
   10 CONTINUE

      ISTART=MAXLEN-I
      CHRSTR(ISTART+1:MAXLEN)=CHRSTR(1:I)
      DO I=1,ISTART
         CHRSTR(I:I)=' '
      ENDDO
      RETURN
      END

      SUBROUTINE LCTRIM(CHRSTR)

!     REMOVE LEADING BLANKS FROM CHRSTR.
      IMPLICIT NONE

!     ARGUMENT:
      CHARACTER CHRSTR*(*)

!     LOCAL VARIABLES:
      INTEGER I,K,ISTART,IMAXLN

      IMAXLN=LEN(CHRSTR)

      DO I=1,IMAXLN
         IF(CHRSTR(I:I).NE.' ')GOTO 10
      ENDDO
   10 CONTINUE

      ISTART=I
      K=1
      DO I=ISTART,IMAXLN
         CHRSTR(K:K)=CHRSTR(I:I)
         K=K+1
      ENDDO

      DO I=IMAXLN+1,IMAXLN+ISTART-1
         CHRSTR(K:K)=' '
         K=K+1
      ENDDO

      RETURN
      END
