      SUBROUTINE WRTALB(VCEN,ILOS,INTRVL,SUBINT,                        &
     &  TDFSUN,TDRSGO,TDFOBS,TDROBS,ALBBOT)

!     WRTALB WRITES SPECTRAL, K-DISTRIBUTION DEPENDENT DIRECT
!     AND (EMBEDDED) DIFFUSE TRANSMITTANCES AND THE SPECTRAL,
!     K-DISTRIBUTION DEPENDENT DIRECT SPHERICAL ALBEDO (FROM
!     THE GROUND) TO OUTPUT FILE "*.acd".
      IMPLICIT NONE

!     ARGUMENTS:
!       VCEN     SPECTRAL-BIN CENTRAL FREQUENCY [CM-1].
!       ILOS     LINE-OF-SIGHT PATH INDEX.
!       SUBINT   K-DISTRIBUTION SUB-INTERVAL WEIGHT.
!       TDFSUN   SUN TO GROUND DIFFUSE SPECTRAL TRANSMITTANCE.
!       TDRSGO   DIRECT SUN-TO-GROUND-TO-OBSERVER TRANSMITTANCE.
!       TDFOBS   OBSERVER TO GROUND "EMBEDDED" DIFFUSE TRANSMITTANCE.
!       TDROBS   OBSERVER TO GROUND DIRECT SPECTRAL TRANSMITTANCE.
!       ALBBOT   MEDIUM SPHERICAL ALBEDO FROM BOTTOM.
      INTEGER INTRVL,ILOS
      REAL VCEN,SUBINT,TDFSUN,TDRSGO,TDFOBS,TDROBS,ALBBOT

!     COMMONS:
      INCLUDE 'IFIL.h'
      IF(BINOUT)THEN
          CALL BINALB(VCEN,ILOS,INTRVL,SUBINT,                          &
     &      TDFSUN,TDRSGO,TDFOBS,TDROBS,ALBBOT)
      ELSE
          WRITE(IALB,'(F9.2,2(1X,I3),1X,F12.6,1X,1P,5E14.4)')           &
     &      VCEN,ILOS,INTRVL,SUBINT,TDFSUN,TDRSGO,TDFOBS,TDROBS,ALBBOT
      ENDIF
      RETURN
      END
