
!     /WSOL/
!       TSSEG    DENSITY-WEIGHTED TEMPERATURE FOR BAND MODEL SPECIES
!                ALONG SOLAR PATHS FROM LINES-OF-SIGHT [K].
!       TSSEGM   DENSITY-WEIGHTED TEMPERATURE FOR BAND MODEL SPECIES
!                ALONG SOLAR PATHS FROM MULTIPLE SCATTER VERTICAL
!                PATH; {TSSEGM(I,J) = TSSEG(I,J,MLOS+1)} [K].
!       PSATM    DENSITY-WEIGHTED PRESSURE FOR BAND MODEL SPECIES
!                ALONG SOLAR PATHS FROM LINES-OF-SIGHT [ATM].
!       PSATMM   DENSITY-WEIGHTED PRESSURE FOR BAND MODEL SPECIES
!                ALONG SOLAR PATHS FROM MULTIPLE SCATTER VERTICAL
!                PATH; {PSATMM(I,J) = PSATM(I,J,MLOS+1)} [ATM].
!       WSPTH    LINE-OF-SIGHT SCATTERING POINT TO SUN MOLECULAR COLUMN
!                AMOUNTS FOR EXTINCTION SPECIES [ATM CM].
!       WSPTHM   MULTIPLE SCATTER VERTICAL PATH SCATTERING POINT
!                TO SUN MOLECULAR COLUMN AMOUNTS FOR EXTINCTION
!                SPECIES; {WSPTHM(I,J) = WSPTH(I,J,MLOS+1)} [ATM CM].
      REAL TSSEG,TSSEGM,PSATM,PSATMM,WSPTH,WSPTHM
      COMMON/WSOL/TSSEG(MMOLT,LAYTWO,MLOS),TSSEGM(MMOLT,LAYDIM),        &
     &            PSATM(MMOLT,LAYTWO,MLOS),PSATMM(MMOLT,LAYDIM),        &
     &  WSPTH(0:MEXTXY,1:LAYTWO,1:MLOS),WSPTHM(0:MEXTXY,1:LAYDIM)
