
!     Y-SPECIES ARE THE USER-DEFINED SPECIES.

!     /YPROP/
!       NMOLY    TOTAL NUMBER OF ACTIVE Y-SPECIES.
!       NMOLT    TOTAL NUMBER OF ACTIVE MOLECULAR SPECIES.
!       NMOLYC   TOTAL NUMBER OF Y-SPECIES (ACTIVE AND DORMANT).
!       NMOLYS   TOTAL NUMBER OF ACTIVE BAND MODEL Y-SPECIES.
!       MAPY_F   MAPPING FROM ACTIVE Y-SPECIES TO FULL Y-SPECIES LIST.
!       MAPY_D   MAPPING FROM ACTIVE Y-SPECIES TO DEFAULT PROFILES.
!       AMWTY    MOLECULAR WEIGHT OF Y-SPECIES [GM/MOL].
!       DOPY     STP DOPPLER HALF-WIDTH PARAMETERS.
!       LYDFLT   .TRUE. IF DEFAULT PROFILES EXIST FOR ALL Y-SPECIES.
      INTEGER NMOLY,NMOLT,NMOLYC,NMOLYS,MAPY_F,MAPY_D
      REAL DOPY,AMWTY
      LOGICAL LYDFLT
      COMMON/YPROP/NMOLY,NMOLT,NMOLYC,NMOLYS,                           &
     &  MAPY_F(MMOLY),MAPY_D(MMOLY),AMWTY(MMOLY),DOPY(MMOLY),LYDFLT
